export const ASSAM_DISTRICTS = [
    "Baksa",
    "Barpeta",
    "Biswanath",
    "Bongaigaon",
    "Cachar",
    "Charaideo",
    "Chirang",
    "Darrang",
    "Dhemaji",
    "Dhubri",
    "Dibrugarh",
    "Dima Hasao",
    "Goalpara",
    "Golaghat",
    "Hailakandi",
    "Hojai",
    "Jorhat",
    "Kamrup",
    "Kamrup Metropolitan",
    "Karbi Anglong",
    "Karimganj",
    "Kokrajhar",
    "Lakhimpur",
    "Majuli",
    "Morigaon",
    "Nagaon",
    "Nalbari",
    "Sivasagar",
    "Sonitpur",
    "South Salmara-Mankachar",
    "Tinsukia",
    "Udalguri",
    "West Karbi Anglong"
];

export const INSTITUTION_TYPES = [
    "Medical College",
    "District Hospital",
    "Sub-Divisional Civil Hospital (SDCH)",
    "Community Health Centre (CHC)",
    "Primary Health Centre (PHC)",
    "Model Hospital",
    "First Referral Unit (FRU)",
    "Urban Health Centre",
    "State Dispensary"
];
