import { GoogleGenAI } from "@google/genai";
import { Patient } from "../types";

// ============================================================================
// API KEY CONFIGURATION
// ============================================================================

const getApiKey = () => {
  const apiKey = import.meta.env.VITE_GEMINI_API_KEY;

  if (!apiKey) {
    console.error('Missing VITE_GEMINI_API_KEY environment variable.');
    console.error('Please add your Gemini API key to the .env file.');
    throw new Error('Gemini API key is not configured. Please check your .env file.');
  }

  return apiKey;
};

const ai = new GoogleGenAI({ apiKey: getApiKey() });

// ============================================================================
// CACHING INFRASTRUCTURE
// ============================================================================

interface CacheEntry {
  result: any;
  timestamp: number;
}

const aiCache = new Map<string, CacheEntry>();
const CACHE_TTL = 5 * 60 * 1000; // 5 minutes

const getCachedResult = (key: string): any | null => {
  const cached = aiCache.get(key);
  if (cached && Date.now() - cached.timestamp < CACHE_TTL) {
    return cached.result;
  }
  return null;
};

const setCachedResult = (key: string, result: any): void => {
  aiCache.set(key, { result, timestamp: Date.now() });
};

// AI Disclaimer for medical outputs
const AI_DISCLAIMER = "\n\n⚠️ AI-Generated Content: This information is generated by AI and should not replace professional clinical judgment. Always verify with current evidence-based guidelines and consult senior clinicians for critical decisions.";

// ============================================================================
// EXISTING AI FUNCTIONS (ENHANCED)
// ============================================================================

export const generatePatientSummary = async (patient: Patient): Promise<string> => {
  const cacheKey = `summary-${patient.id}-${patient.progressNotes.length}`;
  const cached = getCachedResult(cacheKey);
  if (cached) return cached;

  const notes = patient.progressNotes.map(n => `- ${new Date(n.date).toLocaleString()}: ${n.note}`).join('\n');

  const prompt = `
    You are a medical professional specializing in intensive care.
    Generate a concise clinical summary for a patient handoff based on the following details.
    The summary should be in clear, professional language, highlighting the most critical information.
    Format the output as a single paragraph.

    Patient Unit: ${patient.unit}
    Patient Age: ${patient.age} ${patient.ageUnit}
    Gender: ${patient.gender}
    Primary Diagnosis: ${patient.diagnosis}
    Clinical Notes:
    ${notes || 'No notes available.'}
    Current Status: ${patient.outcome}
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    const result = response.text;
    setCachedResult(cacheKey, result);
    return result;
  } catch (error) {
    console.error("Error generating summary with Gemini:", error);
    return "Error: Could not generate summary. The AI model may be unavailable or there might be an issue with the API key.";
  }
};

export const getClinicalInsights = async (patient: Patient): Promise<string> => {
  const cacheKey = `insights-${patient.id}-${patient.diagnosis}`;
  const cached = getCachedResult(cacheKey);
  if (cached) return cached;

  const notes = patient.progressNotes.map(n => `- ${new Date(n.date).toLocaleString()}: ${n.note}`).join('\n');

  const prompt = `
    You are an expert neonatologist and pediatric intensivist.
    Analyze the following patient data and provide clinical insights.
    Focus on potential complications to watch for, suggested immediate actions, and key physiological parameters to monitor.
    Be concise and action-oriented.

    Patient Unit: ${patient.unit}
    Age: ${patient.age} ${patient.ageUnit}
    Diagnosis: ${patient.diagnosis}
    History: ${notes || 'No recent notes.'}

    Output format:
    **Potential Complications**: [List]
    **Care Suggestions**: [List]
    **Monitoring Priorities**: [List]
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.0-flash',
      contents: prompt,
    });
    const result = response.text + AI_DISCLAIMER;
    setCachedResult(cacheKey, result);
    return result;
  } catch (error) {
    console.error("Gemini Error:", error);
    return "Unable to generate insights at this time.";
  }
};

export const predictRisk = async (patient: Patient): Promise<{ riskLevel: 'Low' | 'Medium' | 'High'; justification: string }> => {
  const cacheKey = `risk-${patient.id}-${patient.diagnosis}-${patient.outcome}`;
  const cached = getCachedResult(cacheKey);
  if (cached) return cached;

  const prompt = `
    Evaluate the clinical risk level for this patient based on the diagnosis and age.
    Patient: ${patient.age} ${patient.ageUnit}, Diagnosis: ${patient.diagnosis}, Unit: ${patient.unit}.

    Output strictly in JSON format:
    { "riskLevel": "Low" | "Medium" | "High", "justification": "One sentence explanation" }
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.0-flash',
      contents: prompt,
    });
    const text = response.text.replace(/```json|```/g, '').trim();
    const result = JSON.parse(text);
    setCachedResult(cacheKey, result);
    return result;
  } catch (error) {
    console.error("Gemini Error:", error);
    return { riskLevel: 'Medium', justification: "AI risk assessment unavailable." };
  }
};

// ============================================================================
// CLINICAL DECISION SUPPORT
// ============================================================================

export const generateDifferentialDiagnosis = async (
  symptoms: string,
  age: number,
  ageUnit: string,
  unit: string
): Promise<string> => {
  const cacheKey = `diff-diag-${symptoms}-${age}-${ageUnit}-${unit}`;
  const cached = getCachedResult(cacheKey);
  if (cached) return cached;

  const prompt = `
    You are an expert ${unit} physician.
    Generate a differential diagnosis list for a patient with the following presentation:

    Age: ${age} ${ageUnit}
    Unit: ${unit}
    Symptoms/Presentation: ${symptoms}

    Provide a ranked list (most likely first) of 5-7 possible diagnoses with:
    - Diagnosis name
    - Brief rationale (1-2 sentences)
    - Probability category (High/Moderate/Low)

    Format as a clear, numbered list.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    const result = response.text + AI_DISCLAIMER;
    setCachedResult(cacheKey, result);
    return result;
  } catch (error) {
    console.error("Error generating differential diagnosis:", error);
    return "Unable to generate differential diagnosis at this time.";
  }
};

export const recommendTreatmentProtocol = async (
  diagnosis: string,
  age: number,
  ageUnit: string,
  comorbidities?: string
): Promise<string> => {
  const cacheKey = `treatment-${diagnosis}-${age}-${ageUnit}`;
  const cached = getCachedResult(cacheKey);
  if (cached) return cached;

  const prompt = `
    You are an expert pediatric intensivist.
    Provide evidence-based treatment recommendations for:

    Diagnosis: ${diagnosis}
    Patient Age: ${age} ${ageUnit}
    ${comorbidities ? `Comorbidities: ${comorbidities}` : ''}

    Include:
    1. Initial management steps
    2. Medication recommendations (with age-appropriate dosing considerations)
    3. Monitoring parameters
    4. When to escalate care
    5. Expected course and milestones

    Be specific but concise. Reference evidence-based guidelines when applicable.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    const result = response.text + AI_DISCLAIMER;
    setCachedResult(cacheKey, result);
    return result;
  } catch (error) {
    console.error("Error generating treatment protocol:", error);
    return "Unable to generate treatment protocol at this time.";
  }
};

export const checkDrugInteractions = async (
  medications: string[],
  conditions: string[]
): Promise<string> => {
  const cacheKey = `drug-check-${medications.join(',')}-${conditions.join(',')}`;
  const cached = getCachedResult(cacheKey);
  if (cached) return cached;

  const prompt = `
    You are a clinical pharmacist specializing in pediatric intensive care.
    Check for drug interactions and contraindications:

    Medications: ${medications.join(', ')}
    Patient Conditions: ${conditions.join(', ')}

    Provide:
    1. Major drug-drug interactions (if any)
    2. Drug-disease contraindications (if any)
    3. Dosing considerations for pediatric patients
    4. Monitoring recommendations

    If no significant interactions, state "No major interactions detected."
    Format as clear bullet points with severity ratings (Critical/Moderate/Minor).
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.0-flash',
      contents: prompt,
    });
    const result = response.text + AI_DISCLAIMER;
    setCachedResult(cacheKey, result);
    return result;
  } catch (error) {
    console.error("Error checking drug interactions:", error);
    return "Unable to check drug interactions at this time.";
  }
};

export const calculateMedicationDosage = async (
  medication: string,
  weight: number,
  age: number,
  ageUnit: string,
  indication: string
): Promise<string> => {
  const prompt = `
    You are a pediatric pharmacist.
    Calculate appropriate dosing for:

    Medication: ${medication}
    Patient Weight: ${weight} kg
    Patient Age: ${age} ${ageUnit}
    Indication: ${indication}

    Provide:
    1. Recommended dose (mg/kg or total dose)
    2. Frequency
    3. Route of administration
    4. Maximum dose limits
    5. Key monitoring parameters

    Base recommendations on pediatric dosing guidelines.
    If weight-based dosing, show the calculation.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    return response.text + AI_DISCLAIMER;
  } catch (error) {
    console.error("Error calculating medication dosage:", error);
    return "Unable to calculate medication dosage at this time.";
  }
};

// ============================================================================
// PREDICTIVE ANALYTICS
// ============================================================================

export const detectClinicalDeterioration = async (patient: Patient): Promise<string> => {
  const notes = patient.progressNotes
    .slice(-5)
    .map(n => `${new Date(n.date).toLocaleString()}: ${n.note}`)
    .join('\n');

  const prompt = `
    You are an expert in pediatric early warning systems.
    Analyze the following patient's recent clinical trajectory:

    Patient: ${patient.age} ${patient.ageUnit}, ${patient.unit}
    Diagnosis: ${patient.diagnosis}
    Recent Progress Notes:
    ${notes}

    Assess for signs of clinical deterioration:
    1. Calculate an estimated Early Warning Score (0-10 scale)
    2. Identify concerning trends
    3. Recommend immediate actions if deterioration detected
    4. Suggest intensified monitoring parameters

    Format: Score, Assessment, Recommendations
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    return response.text + AI_DISCLAIMER;
  } catch (error) {
    console.error("Error detecting deterioration:", error);
    return "Unable to assess clinical deterioration at this time.";
  }
};

export const predictLengthOfStay = async (patient: Patient): Promise<string> => {
  const prompt = `
    You are an expert in hospital capacity planning and clinical outcomes.
    Estimate the expected length of stay for:

    Patient: ${patient.age} ${patient.ageUnit}
    Unit: ${patient.unit}
    Diagnosis: ${patient.diagnosis}
    Current Status: ${patient.outcome}
    Days since admission: ${Math.floor((Date.now() - new Date(patient.admissionDate).getTime()) / (1000 * 60 * 60 * 24))}

    Provide:
    1. Estimated remaining days (range)
    2. Key milestones for discharge
    3. Factors that could extend stay
    4. Discharge planning recommendations
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    return response.text + AI_DISCLAIMER;
  } catch (error) {
    console.error("Error predicting length of stay:", error);
    return "Unable to predict length of stay at this time.";
  }
};

export const assessStepDownReadiness = async (patient: Patient): Promise<string> => {
  const recentNotes = patient.progressNotes
    .slice(-3)
    .map(n => `${new Date(n.date).toLocaleString()}: ${n.note}`)
    .join('\n');

  const prompt = `
    You are an expert in pediatric step-down criteria.
    Assess if this patient is ready for step-down from intensive care:

    Patient: ${patient.age} ${patient.ageUnit}
    Unit: ${patient.unit}
    Diagnosis: ${patient.diagnosis}
    Recent Notes:
    ${recentNotes}

    Evaluate:
    1. Hemodynamic stability
    2. Respiratory status
    3. Neurological status
    4. Need for intensive monitoring
    5. Risk of rapid deterioration

    Provide: Ready/Not Ready recommendation with detailed justification.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    return response.text + AI_DISCLAIMER;
  } catch (error) {
    console.error("Error assessing step-down readiness:", error);
    return "Unable to assess step-down readiness at this time.";
  }
};

export const predictReadmissionRisk = async (patient: Patient): Promise<string> => {
  const prompt = `
    You are an expert in pediatric hospital readmissions.
    Assess the 30-day readmission risk for:

    Patient: ${patient.age} ${patient.ageUnit}
    Diagnosis: ${patient.diagnosis}
    Unit: ${patient.unit}
    Current Outcome: ${patient.outcome}

    Analyze:
    1. Disease-specific risk factors
    2. Social/environmental factors
    3. Discharge readiness
    4. Follow-up care adequacy

    Provide: Risk Level (Low/Medium/High) with specific mitigation strategies.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    return response.text + AI_DISCLAIMER;
  } catch (error) {
    console.error("Error predicting readmission risk:", error);
    return "Unable to predict readmission risk at this time.";
  }
};

export const calculateSepsisRisk = async (patient: Patient, vitalSigns?: string): Promise<string> => {
  const prompt = `
    You are an expert in pediatric sepsis recognition.
    Calculate sepsis risk for:

    Patient: ${patient.age} ${patient.ageUnit}
    Diagnosis: ${patient.diagnosis}
    ${vitalSigns ? `Recent Vitals: ${vitalSigns}` : ''}

    Assess for:
    1. Sepsis risk score (Low/Moderate/High/Critical)
    2. SIRS criteria met
    3. End-organ dysfunction signs
    4. Recommended interventions
    5. Timing of reassessment

    Provide immediate actionable guidance if high risk detected.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    return response.text + "⚠️ CRITICAL: Sepsis is a medical emergency. This AI assessment does not replace clinical judgment. Escalate immediately if concerned.";
  } catch (error) {
    console.error("Error calculating sepsis risk:", error);
    return "Unable to calculate sepsis risk at this time.";
  }
};

export const generateEarlyWarningScore = async (patient: Patient): Promise<string> => {
  const recentNote = patient.progressNotes[patient.progressNotes.length - 1];

  const prompt = `
    You are an expert in Pediatric Early Warning Scores (PEWS).
    Calculate an estimated PEWS for:

    Patient: ${patient.age} ${patient.ageUnit}
    Unit: ${patient.unit}
    Diagnosis: ${patient.diagnosis}
    Most Recent Note: ${recentNote ? recentNote.note : 'No recent notes'}

    Provide:
    1. Estimated PEWS score (0-9+ scale)
    2. Score breakdown by category (Behavior, Cardiovascular, Respiratory)
    3. Interpretation and risk level
    4. Recommended actions based on score

    Note: This is an estimation based on documentation. Actual PEWS requires vital signs.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    return response.text + AI_DISCLAIMER;
  } catch (error) {
    console.error("Error generating early warning score:", error);
    return "Unable to generate early warning score at this time.";
  }
};

// ============================================================================
// DOCUMENTATION AI
// ============================================================================

export const generateHandoffNote = async (patient: Patient, shiftType: 'day' | 'night'): Promise<string> => {
  const notes = patient.progressNotes.slice(-3).map(n => `${new Date(n.date).toLocaleString()}: ${n.note}`).join('\n');

  const prompt = `
    You are generating a ${shiftType} shift handoff note in SBAR format.

    Patient: ${patient.name} (${patient.age} ${patient.ageUnit})
    Unit: ${patient.unit}
    Diagnosis: ${patient.diagnosis}
    Current Status: ${patient.outcome}
    Recent Events:
    ${notes}

    Generate a concise SBAR handoff:
    **Situation**: One-line patient summary
    **Background**: Key history and diagnosis
    **Assessment**: Current clinical status and trends
    **Recommendation**: Key actions needed in next ${shiftType === 'day' ? '12' : '12'} hours

    Be specific about time-sensitive tasks and concerns.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    return response.text;
  } catch (error) {
    console.error("Error generating handoff note:", error);
    return "Unable to generate handoff note at this time.";
  }
};

export const generateRoundingSheet = async (patients: Patient[], unit: string): Promise<string> => {
  const patientSummaries = patients
    .filter(p => p.outcome === 'In Progress')
    .map(p => `- ${p.name} (${p.age} ${p.ageUnit}): ${p.diagnosis}`)
    .join('\n');

  const prompt = `
    You are preparing a rounds sheet for the ${unit} team.

    Active Patients:
    ${patientSummaries}

    Create a prioritized rounding list with:
    1. Highest priority patients first (most unstable/complex)
    2. Brief one-liner for each patient
    3. Key decision points for today
    4. Estimated time per patient

    Format as a numbered list ready for morning rounds.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    return response.text;
  } catch (error) {
    console.error("Error generating rounding sheet:", error);
    return "Unable to generate rounding sheet at this time.";
  }
};

export const structureProgressNote = async (rawText: string): Promise<string> => {
  const prompt = `
    You are a medical scribe. Convert this raw clinical note into structured SOAP format:

    Raw Note:
    ${rawText}

    Output format:
    **Subjective**: Patient/family concerns and symptoms
    **Objective**: Clinical findings, vitals, labs
    **Assessment**: Clinical interpretation and diagnosis
    **Plan**: Treatment plan and follow-up

    Clean up grammar and medical terminology. Keep it concise.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    return response.text;
  } catch (error) {
    console.error("Error structuring progress note:", error);
    return "Unable to structure progress note at this time.";
  }
};

export const extractPatientInfoFromText = async (text: string): Promise<any> => {
  const prompt = `
    Extract structured patient information from this clinical text:

    ${text}

    Extract and output as JSON:
    {
      "name": "patient name if mentioned",
      "age": number,
      "ageUnit": "days/weeks/months/years",
      "gender": "Male/Female",
      "diagnosis": "primary diagnosis",
      "symptoms": "key symptoms or presentation",
      "history": "relevant history"
    }

    If information is not present, use null. Output only valid JSON.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    const text = response.text.replace(/```json|```/g, '').trim();
    return JSON.parse(text);
  } catch (error) {
    console.error("Error extracting patient info:", error);
    return null;
  }
};

// ============================================================================
// REPORTING & ANALYTICS
// ============================================================================

export const generateMonthlyReport = async (
  patients: Patient[],
  month: string,
  unit: string,
  institutionName: string
): Promise<string> => {
  const stats = {
    total: patients.length,
    discharged: patients.filter(p => p.outcome === 'Discharged').length,
    deceased: patients.filter(p => p.outcome === 'Deceased').length,
    referred: patients.filter(p => p.outcome === 'Referred').length,
    inProgress: patients.filter(p => p.outcome === 'In Progress').length,
  };

  const prompt = `
    Generate a comprehensive monthly report for:

    Institution: ${institutionName}
    Unit: ${unit}
    Month: ${month}

    Statistics:
    - Total Admissions: ${stats.total}
    - Discharged: ${stats.discharged}
    - Deceased: ${stats.deceased}
    - Referred: ${stats.referred}
    - Currently Admitted: ${stats.inProgress}

    Include:
    1. Executive Summary
    2. Key Performance Metrics
    3. Outcome Analysis
    4. Mortality Review Summary
    5. Recommendations for Quality Improvement

    Format as a professional report suitable for hospital administration.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    return response.text;
  } catch (error) {
    console.error("Error generating monthly report:", error);
    return "Unable to generate monthly report at this time.";
  }
};

export const generateDischargeInstructions = async (patient: Patient): Promise<string> => {
  const prompt = `
    Generate family-friendly discharge instructions for:

    Patient: ${patient.age} ${patient.ageUnit} old child
    Diagnosis: ${patient.diagnosis}

    Include:
    1. **Home Care Instructions** (in simple language)
    2. **Medications** (if applicable, general categories)
    3. **Warning Signs** to watch for (when to seek emergency care)
    4. **Follow-up Care** recommendations
    5. **Activity Restrictions** (if any)
    6. **Feeding/Nutrition** guidance

    Use clear, non-medical language that families can understand.
    Format with bullet points for easy reading.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    return response.text;
  } catch (error) {
    console.error("Error generating discharge instructions:", error);
    return "Unable to generate discharge instructions at this time.";
  }
};

export const generateMortalityReview = async (deceasedPatients: Patient[]): Promise<string> => {
  const patientSummaries = deceasedPatients.map(p =>
    `- ${p.age} ${p.ageUnit}, Diagnosis: ${p.diagnosis}`
  ).join('\n');

  const prompt = `
    Generate a Morbidity & Mortality (M&M) review summary for:

    Deceased Patients:
    ${patientSummaries}

    Analyze:
    1. Common diagnoses leading to mortality
    2. Age distribution analysis
    3. Potential preventable factors (general patterns)
    4. Quality improvement opportunities
    5. System-level recommendations

    Format as a structured M&M report suitable for clinical review.
    Be respectful and focus on learning opportunities.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    return response.text;
  } catch (error) {
    console.error("Error generating mortality review:", error);
    return "Unable to generate mortality review at this time.";
  }
};

export const auditClinicalDocumentation = async (patient: Patient): Promise<string> => {
  const prompt = `
    Audit the clinical documentation completeness for:

    Patient: ${patient.age} ${patient.ageUnit}
    Diagnosis: ${patient.diagnosis}
    Progress Notes: ${patient.progressNotes.length} notes
    Outcome: ${patient.outcome}

    Check for:
    1. Documentation completeness
    2. Missing critical information
    3. Billing/coding opportunities
    4. Quality metric compliance
    5. Recommendations for improved documentation

    Provide actionable feedback for the clinical team.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.0-flash',
      contents: prompt,
    });
    return response.text;
  } catch (error) {
    console.error("Error auditing documentation:", error);
    return "Unable to audit documentation at this time.";
  }
};

// ============================================================================
// SEARCH & INTELLIGENCE
// ============================================================================

export const findSimilarPatients = async (
  patient: Patient,
  allPatients: Patient[]
): Promise<string> => {
  const otherPatients = allPatients
    .filter(p => p.id !== patient.id)
    .slice(0, 50)
    .map(p => `${p.age} ${p.ageUnit}, Diagnosis: ${p.diagnosis}, Outcome: ${p.outcome}`)
    .join('\n');

  const prompt = `
    Find patients similar to:
    Index Patient: ${patient.age} ${patient.ageUnit}, Diagnosis: ${patient.diagnosis}

    From this dataset:
    ${otherPatients}

    Identify the 5 most similar patients based on:
    - Age similarity
    - Diagnosis similarity
    - Clinical complexity

    For each similar patient, explain why they're relevant and what can be learned from their outcome.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    return response.text;
  } catch (error) {
    console.error("Error finding similar patients:", error);
    return "Unable to find similar patients at this time.";
  }
};

// ============================================================================
// EDUCATIONAL SUPPORT
// ============================================================================

export const explainDiagnosis = async (
  diagnosis: string,
  audience: 'doctor' | 'nurse' | 'family'
): Promise<string> => {
  const audienceContext = {
    doctor: "another physician - include pathophysiology and evidence-based management",
    nurse: "nursing staff - focus on care protocols and monitoring",
    family: "patient's family in simple, non-medical language"
  };

  const prompt = `
    Explain "${diagnosis}" to ${audienceContext[audience]}.

    Include:
    ${audience === 'family' ? '1. What it is in simple terms\n2. What causes it\n3. How it\'s treated\n4. What to expect\n5. When to worry' : '1. Clinical overview\n2. Key features\n3. Management approach\n4. Monitoring priorities\n5. Complications to watch for'}

    Keep it ${audience === 'family' ? 'reassuring but honest' : 'clinically focused and evidence-based'}.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    return response.text;
  } catch (error) {
    console.error("Error explaining diagnosis:", error);
    return "Unable to explain diagnosis at this time.";
  }
};

export const suggestClinicalGuidelines = async (diagnosis: string): Promise<string> => {
  const prompt = `
    Provide evidence-based clinical guidelines for: ${diagnosis}

    Include:
    1. Relevant AAP (American Academy of Pediatrics) guidelines
    2. WHO recommendations (if applicable)
    3. Key evidence-based practices
    4. Quality metrics for this condition
    5. References to major clinical trials or guidelines

    Format as a quick reference guide.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    return response.text + AI_DISCLAIMER;
  } catch (error) {
    console.error("Error suggesting guidelines:", error);
    return "Unable to suggest clinical guidelines at this time.";
  }
};

export const answerClinicalQuestion = async (
  question: string,
  patientContext?: Patient
): Promise<string> => {
  const context = patientContext
    ? `\n\nPatient Context: ${patientContext.age} ${patientContext.ageUnit}, ${patientContext.diagnosis}, ${patientContext.unit}`
    : '';

  const prompt = `
    You are a clinical expert assistant.
    Answer this clinical question: ${question}
    ${context}

    Provide:
    1. Direct answer
    2. Evidence basis (if applicable)
    3. Practical clinical pearls
    4. When to seek specialist consultation

    Be concise but thorough.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    return response.text + AI_DISCLAIMER;
  } catch (error) {
    console.error("Error answering clinical question:", error);
    return "Unable to answer clinical question at this time.";
  }
};

// ============================================================================
// DATA VALIDATION
// ============================================================================

export const validatePatientData = async (formData: Partial<Patient>): Promise<string> => {
  const prompt = `
    Validate this patient data for clinical consistency:

    Age: ${formData.age} ${formData.ageUnit}
    Diagnosis: ${formData.diagnosis}
    Unit: ${formData.unit}

    Check for:
    1. Age-appropriate diagnosis
    2. Appropriate unit assignment
    3. Missing critical information
    4. Unusual or concerning combinations

    Provide: "Valid" or list specific concerns with recommendations.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.0-flash',
      contents: prompt,
    });
    return response.text;
  } catch (error) {
    console.error("Error validating patient data:", error);
    return "Unable to validate patient data at this time.";
  }
};

export const suggestDiagnosis = async (
  partialInput: string,
  age?: number,
  ageUnit?: string,
  unit?: string
): Promise<string[]> => {
  const context = age && ageUnit && unit
    ? `for a ${age} ${ageUnit} old patient in ${unit}`
    : '';

  const prompt = `
    Suggest diagnoses that match "${partialInput}" ${context}.

    Return 5-7 most relevant diagnoses as a simple comma-separated list.
    Use standard medical terminology.
    Only return the diagnosis names, nothing else.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.0-flash',
      contents: prompt,
    });
    const suggestions = response.text
      .split(',')
      .map(s => s.trim())
      .filter(s => s.length > 0)
      .slice(0, 7);
    return suggestions;
  } catch (error) {
    console.error("Error suggesting diagnoses:", error);
    return [];
  }
};

// ============================================================================
// CHART ANALYTICS AI
// ============================================================================

export const explainChartData = async (
  chartTitle: string,
  chartType: string,
  dataPoints: { label: string; value: number | string }[],
  context?: string
): Promise<string> => {
  const dataString = dataPoints
    .map(d => `${d.label}: ${d.value}`)
    .join('\n');

  const cacheKey = `chart-explain-${chartTitle}-${JSON.stringify(dataPoints).slice(0, 100)}`;
  const cached = getCachedResult(cacheKey);
  if (cached) return cached;

  const prompt = `
    You are NeolinkAI, an expert healthcare analytics assistant for NICU/PICU.
    Analyze this ${chartType} chart data and provide clinically relevant insights.

    Chart Title: ${chartTitle}
    ${context ? `Context: ${context}` : ''}
    
    Data:
    ${dataString}

    Provide a concise analysis including:
    1. **Key Insights** - What does this data tell us? (2-3 bullet points)
    2. **Trends** - Any notable patterns or trends
    3. **Clinical Implications** - What should clinicians pay attention to?
    4. **Recommendations** - Any actionable suggestions

    Keep the response concise (under 200 words) and clinically focused.
    Use simple bullet points. Be specific to the numbers shown.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.0-flash',
      contents: prompt,
    });
    const result = response.text + AI_DISCLAIMER;
    setCachedResult(cacheKey, result);
    return result;
  } catch (error) {
    console.error("Error explaining chart data:", error);
    return "Unable to generate chart explanation at this time. Please try again.";
  }
};

// ============================================================================
// UTILITY EXPORTS
// ============================================================================

export const clearAICache = () => {
  aiCache.clear();
  console.log('AI cache cleared');
};

export const getAICacheStats = () => {
  return {
    size: aiCache.size,
    entries: Array.from(aiCache.keys())
  };
};
