import { Patient } from "../types";

// ============================================================================
// OPENAI API CONFIGURATION - GPT-5.2
// ============================================================================

const getApiKey = () => {
  const apiKey = import.meta.env.VITE_OPENAI_API_KEY;

  if (!apiKey) {
    console.error('Missing VITE_OPENAI_API_KEY environment variable.');
    console.error('Please add your OpenAI API key to the .env file.');
    throw new Error('OpenAI API key is not configured. Please check your .env file.');
  }

  return apiKey;
};

// OpenAI Model Configuration
const OPENAI_MODEL = 'gpt-5.2'; // Primary model
const OPENAI_MODEL_FAST = 'gpt-4o'; // Fallback for faster responses
const OPENAI_MODEL_MINI = 'gpt-4o-mini'; // For simple tasks

// Helper function to call OpenAI GPT
const callOpenAI = async (
  prompt: string,
  systemPrompt?: string,
  options?: {
    model?: string;
    temperature?: number;
    maxTokens?: number;
    jsonMode?: boolean;
  }
): Promise<string> => {
  const apiKey = getApiKey();
  const model = options?.model || OPENAI_MODEL;

  // Determine if this is a newer model that uses max_completion_tokens
  const isNewerModel = model.startsWith('gpt-5') || model.startsWith('o1') || model.startsWith('o3');
  const tokenParam = isNewerModel ? 'max_completion_tokens' : 'max_tokens';

  const requestBody: any = {
    model,
    messages: [
      ...(systemPrompt ? [{ role: 'system', content: systemPrompt }] : []),
      { role: 'user', content: prompt }
    ],
    temperature: options?.temperature ?? 0.3,
    [tokenParam]: options?.maxTokens ?? 2000
  };

  // Add JSON mode if requested
  if (options?.jsonMode) {
    requestBody.response_format = { type: 'json_object' };
  }

  try {
    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`
      },
      body: JSON.stringify(requestBody)
    });

    if (!response.ok) {
      const error = await response.json();
      console.error('OpenAI API Error:', error);

      // If GPT-5.2 fails, try fallback to GPT-4o
      if (model === OPENAI_MODEL && (error.error?.code === 'model_not_found' || error.error?.message?.includes('not supported'))) {
        console.warn('GPT-5.2 not available or incompatible, falling back to GPT-4o...');
        return callOpenAI(prompt, systemPrompt, { ...options, model: OPENAI_MODEL_FAST });
      }

      throw new Error(error.error?.message || 'OpenAI API request failed');
    }

    const data = await response.json();
    return data.choices?.[0]?.message?.content?.trim() || '';
  } catch (error: any) {
    console.error('OpenAI request failed:', error);
    throw error;
  }
};

// ============================================================================
// CACHING INFRASTRUCTURE
// ============================================================================

interface CacheEntry {
  result: any;
  timestamp: number;
}

const aiCache = new Map<string, CacheEntry>();
const CACHE_TTL = 5 * 60 * 1000; // 5 minutes

const getCachedResult = (key: string): any | null => {
  const cached = aiCache.get(key);
  if (cached && Date.now() - cached.timestamp < CACHE_TTL) {
    return cached.result;
  }
  return null;
};

const setCachedResult = (key: string, result: any): void => {
  aiCache.set(key, { result, timestamp: Date.now() });
};

// AI Disclaimer for medical outputs
const AI_DISCLAIMER = "\n\n⚠️ AI-Generated Content: This information is generated by AI and should not replace professional clinical judgment. Always verify with current evidence-based guidelines and consult senior clinicians for critical decisions.";

// System prompt for medical AI
const MEDICAL_SYSTEM_PROMPT = `You are an expert neonatologist and pediatric intensivist AI assistant. You provide evidence-based, clinically accurate information for NICU/PICU care. Be concise, professional, and actionable. Always prioritize patient safety.`;

// ============================================================================
// PATIENT SUMMARY & INSIGHTS
// ============================================================================

export const generatePatientSummary = async (patient: Patient): Promise<string> => {
  const cacheKey = `summary-v2.0-${patient.id}-${patient.progressNotes.length}`;
  const cached = getCachedResult(cacheKey);
  if (cached) return cached;

  const notes = patient.progressNotes.map(n => `${new Date(n.date).toLocaleString()}: ${n.note || 'Vitals and examination recorded'}`).join('\n');

  const currentAge = patient.dateOfBirth
    ? `${Math.floor((Date.now() - new Date(patient.dateOfBirth).getTime()) / (1000 * 60 * 60 * 24))} days`
    : `${patient.age} ${patient.ageUnit}`;

  const prompt = `Generate a clinical summary with the following EXACT format. Follow these rules strictly:

CRITICAL RULES:
- NO bullet points
- NO dashes (-)
- NO asterisks (*)
- NO dots at line starts
- NO bars (|, =, _)
- ONLY use section headings and paragraph text
- Keep it simple and clean

OUTPUT THIS EXACT STRUCTURE:

PATIENT PARTICULARS
Name: ${patient.name}
Age: ${currentAge}
Gender: ${patient.gender}
Birth Weight: ${patient.birthWeight ? `${patient.birthWeight} kg` : 'Not recorded'}
Admission Weight: ${patient.weightOnAdmission ? `${patient.weightOnAdmission} kg` : 'Not recorded'}
Admission Date: ${new Date(patient.admissionDate).toLocaleDateString()}
Indication for Admission: ${patient.indicationsForAdmission?.join(', ') || patient.customIndication || patient.diagnosis}
Unit: ${patient.unit}

DIAGNOSIS
${patient.diagnosis}

CLINICAL SUMMARY
Based on these notes: ${notes || 'No detailed clinical notes available'}
Write 2-3 sentences describing the patient's hospital course and key clinical events in paragraph format.

CURRENT STATUS
Write 2-3 sentences describing current clinical condition and stability in paragraph format.

ADVICE
Write 2-4 sentences with management recommendations and follow-up plan in paragraph format. Include monitoring parameters and key actions needed.

REMEMBER: Use ONLY the section headings shown above followed by paragraph text. NO symbols, NO bullets, NO dashes, NO dots except in sentences.`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT);
    setCachedResult(cacheKey, result);
    return result;
  } catch (error) {
    console.error("Error generating summary with OpenAI:", error);
    return "Error: Could not generate summary. The AI model may be unavailable or there might be an issue with the API key.";
  }
};

export const getClinicalInsights = async (patient: Patient): Promise<string> => {
  const cacheKey = `insights-${patient.id}-${patient.diagnosis}`;
  const cached = getCachedResult(cacheKey);
  if (cached) return cached;

  const notes = patient.progressNotes.map(n => `- ${new Date(n.date).toLocaleString()}: ${n.note}`).join('\n');

  const prompt = `Analyze the following patient data and provide clinical insights.
Focus on potential complications to watch for, suggested immediate actions, and key physiological parameters to monitor.
Be concise and action-oriented.

Patient Unit: ${patient.unit}
Age: ${patient.age} ${patient.ageUnit}
Diagnosis: ${patient.diagnosis}
History: ${notes || 'No recent notes.'}

Output format:
**Potential Complications**: [List]
**Care Suggestions**: [List]
**Monitoring Priorities**: [List]`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT);
    const finalResult = result + AI_DISCLAIMER;
    setCachedResult(cacheKey, finalResult);
    return finalResult;
  } catch (error) {
    console.error("OpenAI Error:", error);
    return "Unable to generate insights at this time.";
  }
};

export const predictRisk = async (patient: Patient): Promise<{ riskLevel: 'Low' | 'Medium' | 'High'; justification: string }> => {
  const cacheKey = `risk-${patient.id}-${patient.diagnosis}-${patient.outcome}`;
  const cached = getCachedResult(cacheKey);
  if (cached) return cached;

  const prompt = `Evaluate the clinical risk level for this patient based on the diagnosis and age.
Patient: ${patient.age} ${patient.ageUnit}, Diagnosis: ${patient.diagnosis}, Unit: ${patient.unit}.

Output strictly in JSON format:
{ "riskLevel": "Low" | "Medium" | "High", "justification": "One sentence explanation" }`;

  try {
    const response = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT, { jsonMode: true });
    const text = response.replace(/```json|```/g, '').trim();
    const result = JSON.parse(text);
    setCachedResult(cacheKey, result);
    return result;
  } catch (error) {
    console.error("OpenAI Error:", error);
    return { riskLevel: 'Medium', justification: "AI risk assessment unavailable." };
  }
};

// ============================================================================
// CLINICAL DECISION SUPPORT
// ============================================================================

export const generateDifferentialDiagnosis = async (
  symptoms: string,
  age: number,
  ageUnit: string,
  unit: string
): Promise<string> => {
  const cacheKey = `diff-diag-${symptoms}-${age}-${ageUnit}-${unit}`;
  const cached = getCachedResult(cacheKey);
  if (cached) return cached;

  const prompt = `You are an expert ${unit} physician.
Generate a differential diagnosis list for a patient with the following presentation:

Age: ${age} ${ageUnit}
Unit: ${unit}
Symptoms/Presentation: ${symptoms}

Provide a ranked list (most likely first) of 5-7 possible diagnoses with:
- Diagnosis name
- Brief rationale (1-2 sentences)
- Probability category (High/Moderate/Low)

Format as a clear, numbered list.`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT);
    const finalResult = result + AI_DISCLAIMER;
    setCachedResult(cacheKey, finalResult);
    return finalResult;
  } catch (error) {
    console.error("Error generating differential diagnosis:", error);
    return "Unable to generate differential diagnosis at this time.";
  }
};

export const recommendTreatmentProtocol = async (
  diagnosis: string,
  age: number,
  ageUnit: string,
  comorbidities?: string
): Promise<string> => {
  const cacheKey = `treatment-${diagnosis}-${age}-${ageUnit}`;
  const cached = getCachedResult(cacheKey);
  if (cached) return cached;

  const prompt = `Provide evidence-based treatment recommendations for:

Diagnosis: ${diagnosis}
Patient Age: ${age} ${ageUnit}
${comorbidities ? `Comorbidities: ${comorbidities}` : ''}

Include:
1. Initial management steps
2. Medication recommendations (with age-appropriate dosing considerations)
3. Monitoring parameters
4. When to escalate care
5. Expected course and milestones

Be specific but concise. Reference evidence-based guidelines when applicable.`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT);
    const finalResult = result + AI_DISCLAIMER;
    setCachedResult(cacheKey, finalResult);
    return finalResult;
  } catch (error) {
    console.error("Error generating treatment protocol:", error);
    return "Unable to generate treatment protocol at this time.";
  }
};

export const checkDrugInteractions = async (
  medications: string[],
  conditions: string[]
): Promise<string> => {
  const cacheKey = `drug-check-${medications.join(',')}-${conditions.join(',')}`;
  const cached = getCachedResult(cacheKey);
  if (cached) return cached;

  const prompt = `You are a clinical pharmacist specializing in pediatric intensive care.
Check for drug interactions and contraindications:

Medications: ${medications.join(', ')}
Patient Conditions: ${conditions.join(', ')}

Provide:
1. Major drug-drug interactions (if any)
2. Drug-disease contraindications (if any)
3. Dosing considerations for pediatric patients
4. Monitoring recommendations

If no significant interactions, state "No major interactions detected."
Format as clear bullet points with severity ratings (Critical/Moderate/Minor).`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT);
    const finalResult = result + AI_DISCLAIMER;
    setCachedResult(cacheKey, finalResult);
    return finalResult;
  } catch (error) {
    console.error("Error checking drug interactions:", error);
    return "Unable to check drug interactions at this time.";
  }
};

export const calculateMedicationDosage = async (
  medication: string,
  weight: number,
  age: number,
  ageUnit: string,
  indication: string
): Promise<string> => {
  const prompt = `You are a pediatric pharmacist.
Calculate appropriate dosing for:

Medication: ${medication}
Patient Weight: ${weight} kg
Patient Age: ${age} ${ageUnit}
Indication: ${indication}

Provide:
1. Recommended dose (mg/kg or total dose)
2. Frequency
3. Route of administration
4. Maximum dose limits
5. Key monitoring parameters

Base recommendations on pediatric dosing guidelines.
If weight-based dosing, show the calculation.`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT);
    return result + AI_DISCLAIMER;
  } catch (error) {
    console.error("Error calculating medication dosage:", error);
    return "Unable to calculate medication dosage at this time.";
  }
};

// ============================================================================
// PREDICTIVE ANALYTICS
// ============================================================================

export const detectClinicalDeterioration = async (patient: Patient): Promise<string> => {
  const notes = patient.progressNotes
    .slice(-5)
    .map(n => `${new Date(n.date).toLocaleString()}: ${n.note}`)
    .join('\n');

  const prompt = `You are an expert in pediatric early warning systems.
Analyze the following patient's recent clinical trajectory:

Patient: ${patient.age} ${patient.ageUnit}, ${patient.unit}
Diagnosis: ${patient.diagnosis}
Recent Progress Notes:
${notes}

Assess for signs of clinical deterioration:
1. Calculate an estimated Early Warning Score (0-10 scale)
2. Identify concerning trends
3. Recommend immediate actions if deterioration detected
4. Suggest intensified monitoring parameters

Format: Score, Assessment, Recommendations`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT);
    return result + AI_DISCLAIMER;
  } catch (error) {
    console.error("Error detecting deterioration:", error);
    return "Unable to assess clinical deterioration at this time.";
  }
};

export const predictLengthOfStay = async (patient: Patient): Promise<string> => {
  const prompt = `You are an expert in hospital capacity planning and clinical outcomes.
Estimate the expected length of stay for:

Patient: ${patient.age} ${patient.ageUnit}
Unit: ${patient.unit}
Diagnosis: ${patient.diagnosis}
Current Status: ${patient.outcome}
Days since admission: ${Math.floor((Date.now() - new Date(patient.admissionDate).getTime()) / (1000 * 60 * 60 * 24))}

Provide:
1. Estimated remaining days (range)
2. Key milestones for discharge
3. Factors that could extend stay
4. Discharge planning recommendations`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT);
    return result + AI_DISCLAIMER;
  } catch (error) {
    console.error("Error predicting length of stay:", error);
    return "Unable to predict length of stay at this time.";
  }
};

export const assessStepDownReadiness = async (patient: Patient): Promise<string> => {
  const recentNotes = patient.progressNotes
    .slice(-3)
    .map(n => `${new Date(n.date).toLocaleString()}: ${n.note}`)
    .join('\n');

  const prompt = `You are an expert in pediatric step-down criteria.
Assess if this patient is ready for step-down from intensive care:

Patient: ${patient.age} ${patient.ageUnit}
Unit: ${patient.unit}
Diagnosis: ${patient.diagnosis}
Recent Notes:
${recentNotes}

Evaluate:
1. Hemodynamic stability
2. Respiratory status
3. Neurological status
4. Need for intensive monitoring
5. Risk of rapid deterioration

Provide: Ready/Not Ready recommendation with detailed justification.`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT);
    return result + AI_DISCLAIMER;
  } catch (error) {
    console.error("Error assessing step-down readiness:", error);
    return "Unable to assess step-down readiness at this time.";
  }
};

export const predictReadmissionRisk = async (patient: Patient): Promise<string> => {
  const prompt = `You are an expert in pediatric hospital readmissions.
Assess the 30-day readmission risk for:

Patient: ${patient.age} ${patient.ageUnit}
Diagnosis: ${patient.diagnosis}
Unit: ${patient.unit}
Current Outcome: ${patient.outcome}

Analyze:
1. Disease-specific risk factors
2. Social/environmental factors
3. Discharge readiness
4. Follow-up care adequacy

Provide: Risk Level (Low/Medium/High) with specific mitigation strategies.`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT);
    return result + AI_DISCLAIMER;
  } catch (error) {
    console.error("Error predicting readmission risk:", error);
    return "Unable to predict readmission risk at this time.";
  }
};

export const calculateSepsisRisk = async (patient: Patient, vitalSigns?: string): Promise<string> => {
  const prompt = `You are an expert in pediatric sepsis recognition.
Calculate sepsis risk for:

Patient: ${patient.age} ${patient.ageUnit}
Diagnosis: ${patient.diagnosis}
${vitalSigns ? `Recent Vitals: ${vitalSigns}` : ''}

Assess for:
1. Sepsis risk score (Low/Moderate/High/Critical)
2. SIRS criteria met
3. End-organ dysfunction signs
4. Recommended interventions
5. Timing of reassessment

Provide immediate actionable guidance if high risk detected.`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT);
    return result + "\n\n⚠️ CRITICAL: Sepsis is a medical emergency. This AI assessment does not replace clinical judgment. Escalate immediately if concerned.";
  } catch (error) {
    console.error("Error calculating sepsis risk:", error);
    return "Unable to calculate sepsis risk at this time.";
  }
};

export const generateEarlyWarningScore = async (patient: Patient): Promise<string> => {
  const recentNote = patient.progressNotes[patient.progressNotes.length - 1];

  const prompt = `You are an expert in Pediatric Early Warning Scores (PEWS).
Calculate an estimated PEWS for:

Patient: ${patient.age} ${patient.ageUnit}
Unit: ${patient.unit}
Diagnosis: ${patient.diagnosis}
Most Recent Note: ${recentNote ? recentNote.note : 'No recent notes'}

Provide:
1. Estimated PEWS score (0-9+ scale)
2. Score breakdown by category (Behavior, Cardiovascular, Respiratory)
3. Interpretation and risk level
4. Recommended actions based on score

Note: This is an estimation based on documentation. Actual PEWS requires vital signs.`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT);
    return result + AI_DISCLAIMER;
  } catch (error) {
    console.error("Error generating early warning score:", error);
    return "Unable to generate early warning score at this time.";
  }
};

// ============================================================================
// DOCUMENTATION AI
// ============================================================================

export const generateHandoffNote = async (patient: Patient, shiftType: 'day' | 'night'): Promise<string> => {
  const notes = patient.progressNotes.slice(-3).map(n => `${new Date(n.date).toLocaleString()}: ${n.note}`).join('\n');

  const prompt = `Generate a ${shiftType} shift handoff note in SBAR format.

Patient: ${patient.name} (${patient.age} ${patient.ageUnit})
Unit: ${patient.unit}
Diagnosis: ${patient.diagnosis}
Current Status: ${patient.outcome}
Recent Events:
${notes}

Generate a concise SBAR handoff:
**Situation**: One-line patient summary
**Background**: Key history and diagnosis
**Assessment**: Current clinical status and trends
**Recommendation**: Key actions needed in next 12 hours

Be specific about time-sensitive tasks and concerns.`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT);
    return result;
  } catch (error) {
    console.error("Error generating handoff note:", error);
    return "Unable to generate handoff note at this time.";
  }
};

export const generateRoundingSheet = async (patients: Patient[], unit: string): Promise<string> => {
  const patientSummaries = patients
    .filter(p => p.outcome === 'In Progress')
    .map(p => `- ${p.name} (${p.age} ${p.ageUnit}): ${p.diagnosis}`)
    .join('\n');

  const prompt = `Prepare a rounds sheet for the ${unit} team.

Active Patients:
${patientSummaries}

Create a prioritized rounding list with:
1. Highest priority patients first (most unstable/complex)
2. Brief one-liner for each patient
3. Key decision points for today
4. Estimated time per patient

Format as a numbered list ready for morning rounds.`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT);
    return result;
  } catch (error) {
    console.error("Error generating rounding sheet:", error);
    return "Unable to generate rounding sheet at this time.";
  }
};

export const structureProgressNote = async (rawText: string): Promise<string> => {
  const prompt = `Convert this raw clinical note into structured SOAP format:

Raw Note:
${rawText}

Output format:
**Subjective**: Patient/family concerns and symptoms
**Objective**: Clinical findings, vitals, labs
**Assessment**: Clinical interpretation and diagnosis
**Plan**: Treatment plan and follow-up

Clean up grammar and medical terminology. Keep it concise.`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT);
    return result;
  } catch (error) {
    console.error("Error structuring progress note:", error);
    return "Unable to structure progress note at this time.";
  }
};

export const extractPatientInfoFromText = async (text: string): Promise<any> => {
  const prompt = `Extract structured patient information from this clinical text:

${text}

Extract and output as JSON:
{
  "name": "patient name if mentioned",
  "age": number,
  "ageUnit": "days/weeks/months/years",
  "gender": "Male/Female",
  "diagnosis": "primary diagnosis",
  "symptoms": "key symptoms or presentation",
  "history": "relevant history"
}

If information is not present, use null. Output only valid JSON.`;

  try {
    const response = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT, { jsonMode: true });
    const cleaned = response.replace(/```json|```/g, '').trim();
    return JSON.parse(cleaned);
  } catch (error) {
    console.error("Error extracting patient info:", error);
    return null;
  }
};

// ============================================================================
// REPORTING & ANALYTICS
// ============================================================================

export const generateMonthlyReport = async (
  patients: Patient[],
  month: string,
  unit: string,
  institutionName: string
): Promise<string> => {
  const stats = {
    total: patients.length,
    discharged: patients.filter(p => p.outcome === 'Discharged').length,
    deceased: patients.filter(p => p.outcome === 'Deceased').length,
    referred: patients.filter(p => p.outcome === 'Referred').length,
    inProgress: patients.filter(p => p.outcome === 'In Progress').length,
  };

  const prompt = `Generate a comprehensive monthly report for:

Institution: ${institutionName}
Unit: ${unit}
Month: ${month}

Statistics:
- Total Admissions: ${stats.total}
- Discharged: ${stats.discharged}
- Deceased: ${stats.deceased}
- Referred: ${stats.referred}
- Currently Admitted: ${stats.inProgress}

Include:
1. Executive Summary
2. Key Performance Metrics
3. Outcome Analysis
4. Mortality Review Summary
5. Recommendations for Quality Improvement

Format as a professional report suitable for hospital administration.`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT, { maxTokens: 3000 });
    return result;
  } catch (error) {
    console.error("Error generating monthly report:", error);
    return "Unable to generate monthly report at this time.";
  }
};

export const generateDischargeInstructions = async (patient: Patient): Promise<string> => {
  const prompt = `Generate family-friendly discharge instructions for:

Patient: ${patient.age} ${patient.ageUnit} old child
Diagnosis: ${patient.diagnosis}

Include:
1. **Home Care Instructions** (in simple language)
2. **Medications** (if applicable, general categories)
3. **Warning Signs** to watch for (when to seek emergency care)
4. **Follow-up Care** recommendations
5. **Activity Restrictions** (if any)
6. **Feeding/Nutrition** guidance

Use clear, non-medical language that families can understand.
Format with bullet points for easy reading.`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT);
    return result;
  } catch (error) {
    console.error("Error generating discharge instructions:", error);
    return "Unable to generate discharge instructions at this time.";
  }
};

export const generateMortalityReview = async (deceasedPatients: Patient[]): Promise<string> => {
  const patientSummaries = deceasedPatients.map(p =>
    `- ${p.age} ${p.ageUnit}, Diagnosis: ${p.diagnosis}`
  ).join('\n');

  const prompt = `Generate a Morbidity & Mortality (M&M) review summary for:

Deceased Patients:
${patientSummaries}

Analyze:
1. Common diagnoses leading to mortality
2. Age distribution analysis
3. Potential preventable factors (general patterns)
4. Quality improvement opportunities
5. System-level recommendations

Format as a structured M&M report suitable for clinical review.
Be respectful and focus on learning opportunities.`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT, { maxTokens: 3000 });
    return result;
  } catch (error) {
    console.error("Error generating mortality review:", error);
    return "Unable to generate mortality review at this time.";
  }
};

export const auditClinicalDocumentation = async (patient: Patient): Promise<string> => {
  const prompt = `Audit the clinical documentation completeness for:

Patient: ${patient.age} ${patient.ageUnit}
Diagnosis: ${patient.diagnosis}
Progress Notes: ${patient.progressNotes.length} notes
Outcome: ${patient.outcome}

Check for:
1. Documentation completeness
2. Missing critical information
3. Billing/coding opportunities
4. Quality metric compliance
5. Recommendations for improved documentation

Provide actionable feedback for the clinical team.`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT);
    return result;
  } catch (error) {
    console.error("Error auditing documentation:", error);
    return "Unable to audit documentation at this time.";
  }
};

// ============================================================================
// SEARCH & INTELLIGENCE
// ============================================================================

export const findSimilarPatients = async (
  patient: Patient,
  allPatients: Patient[]
): Promise<string> => {
  const otherPatients = allPatients
    .filter(p => p.id !== patient.id)
    .slice(0, 50)
    .map(p => `${p.age} ${p.ageUnit}, Diagnosis: ${p.diagnosis}, Outcome: ${p.outcome}`)
    .join('\n');

  const prompt = `Find patients similar to:
Index Patient: ${patient.age} ${patient.ageUnit}, Diagnosis: ${patient.diagnosis}

From this dataset:
${otherPatients}

Identify the 5 most similar patients based on:
- Age similarity
- Diagnosis similarity
- Clinical complexity

For each similar patient, explain why they're relevant and what can be learned from their outcome.`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT);
    return result;
  } catch (error) {
    console.error("Error finding similar patients:", error);
    return "Unable to find similar patients at this time.";
  }
};

// ============================================================================
// EDUCATIONAL SUPPORT
// ============================================================================

export const explainDiagnosis = async (
  diagnosis: string,
  audience: 'doctor' | 'nurse' | 'family'
): Promise<string> => {
  const audienceContext = {
    doctor: "another physician - include pathophysiology and evidence-based management",
    nurse: "nursing staff - focus on care protocols and monitoring",
    family: "patient's family in simple, non-medical language"
  };

  const prompt = `Explain "${diagnosis}" to ${audienceContext[audience]}.

Include:
${audience === 'family' ? '1. What it is in simple terms\n2. What causes it\n3. How it\'s treated\n4. What to expect\n5. When to worry' : '1. Clinical overview\n2. Key features\n3. Management approach\n4. Monitoring priorities\n5. Complications to watch for'}

Keep it ${audience === 'family' ? 'reassuring but honest' : 'clinically focused and evidence-based'}.`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT);
    return result;
  } catch (error) {
    console.error("Error explaining diagnosis:", error);
    return "Unable to explain diagnosis at this time.";
  }
};

export const suggestClinicalGuidelines = async (diagnosis: string): Promise<string> => {
  const prompt = `Provide evidence-based clinical guidelines for: ${diagnosis}

Include:
1. Relevant AAP (American Academy of Pediatrics) guidelines
2. WHO recommendations (if applicable)
3. Key evidence-based practices
4. Quality metrics for this condition
5. References to major clinical trials or guidelines

Format as a quick reference guide.`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT);
    return result + AI_DISCLAIMER;
  } catch (error) {
    console.error("Error suggesting guidelines:", error);
    return "Unable to suggest clinical guidelines at this time.";
  }
};

export const answerClinicalQuestion = async (
  question: string,
  patientContext?: Patient
): Promise<string> => {
  const context = patientContext
    ? `\n\nPatient Context: ${patientContext.age} ${patientContext.ageUnit}, ${patientContext.diagnosis}, ${patientContext.unit}`
    : '';

  const prompt = `Answer this clinical question: ${question}
${context}

Provide:
1. Direct answer
2. Evidence basis (if applicable)
3. Practical clinical pearls
4. When to seek specialist consultation

Be concise but thorough.`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT);
    return result + AI_DISCLAIMER;
  } catch (error) {
    console.error("Error answering clinical question:", error);
    return "Unable to answer clinical question at this time.";
  }
};

// ============================================================================
// DATA VALIDATION
// ============================================================================

export const validatePatientData = async (formData: Partial<Patient>): Promise<string> => {
  const prompt = `Validate this patient data for clinical consistency:

Age: ${formData.age} ${formData.ageUnit}
Diagnosis: ${formData.diagnosis}
Unit: ${formData.unit}

Check for:
1. Age-appropriate diagnosis
2. Appropriate unit assignment
3. Missing critical information
4. Unusual or concerning combinations

Provide: "Valid" or list specific concerns with recommendations.`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT, { model: OPENAI_MODEL_FAST });
    return result;
  } catch (error) {
    console.error("Error validating patient data:", error);
    return "Unable to validate patient data at this time.";
  }
};

export const suggestDiagnosis = async (
  partialInput: string,
  age?: number,
  ageUnit?: string,
  unit?: string
): Promise<string[]> => {
  const context = age && ageUnit && unit
    ? `for a ${age} ${ageUnit} old patient in ${unit}`
    : '';

  const prompt = `Suggest diagnoses that match "${partialInput}" ${context}.

Return 5-7 most relevant diagnoses as a simple comma-separated list.
Use standard medical terminology.
Only return the diagnosis names, nothing else.`;

  try {
    const response = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT, { model: OPENAI_MODEL_FAST });
    const suggestions = response
      .split(',')
      .map(s => s.trim())
      .filter(s => s.length > 0)
      .slice(0, 7);
    return suggestions;
  } catch (error) {
    console.error("Error suggesting diagnoses:", error);
    return [];
  }
};

// ============================================================================
// CHART ANALYTICS AI
// ============================================================================

export const explainChartData = async (
  chartTitle: string,
  chartType: string,
  dataPoints: { label: string; value: number | string }[],
  context?: string
): Promise<string> => {
  const dataString = dataPoints
    .map(d => `${d.label}: ${d.value}`)
    .join('\n');

  const cacheKey = `chart-explain-${chartTitle}-${JSON.stringify(dataPoints).slice(0, 100)}`;
  const cached = getCachedResult(cacheKey);
  if (cached) return cached;

  const prompt = `Analyze this ${chartType} chart data and provide clinically relevant insights.

Chart Title: ${chartTitle}
${context ? `Context: ${context}` : ''}

Data:
${dataString}

Provide a concise analysis including:
1. **Key Insights** - What does this data tell us? (2-3 bullet points)
2. **Trends** - Any notable patterns or trends
3. **Clinical Implications** - What should clinicians pay attention to?
4. **Recommendations** - Any actionable suggestions

Keep the response concise (under 200 words) and clinically focused.
Use simple bullet points. Be specific to the numbers shown.`;

  try {
    const result = await callOpenAI(
      prompt,
      'You are NeolinkAI, an expert healthcare analytics assistant for NICU/PICU. Provide concise, clinically relevant insights. Do not use markdown formatting.'
    );
    const finalResult = result + AI_DISCLAIMER;
    setCachedResult(cacheKey, finalResult);
    console.log("✅ Chart explanation generated using OpenAI GPT-5.2");
    return finalResult;
  } catch (error) {
    console.error("Error explaining chart data:", error);
    return "Unable to generate chart explanation at this time. Please try again.";
  }
};

// ============================================================================
// DEATH DIAGNOSIS INTERPRETATION
// ============================================================================

export const interpretDeathDiagnosis = async (
  fullDiagnosis: string,
  patientAge: number,
  patientAgeUnit: string,
  unit: string
): Promise<string> => {
  const cacheKey = `death-diagnosis-${fullDiagnosis.slice(0, 50)}`;
  const cached = getCachedResult(cacheKey);
  if (cached) return cached;

  const prompt = `You are an expert medical analyst specializing in mortality documentation for NICU/PICU.

Analyze this detailed death diagnosis and provide a concise, structured summary for clinical analytics and mortality reporting.

Patient: ${patientAge} ${patientAgeUnit} old
Unit: ${unit}

Full Diagnosis at Time of Death:
${fullDiagnosis}

Generate a concise, professional summary (2-3 sentences maximum) that includes:
1. Primary cause of death (most important)
2. Key contributing factors
3. Brief clinical context if relevant

Requirements:
- Use standard medical terminology
- Be objective and factual
- Focus on causation, not description
- Maximum 3 sentences
- Suitable for mortality analytics and review

Output ONLY the concise diagnosis summary, nothing else.`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT);
    const trimmedResult = result.trim();
    setCachedResult(cacheKey, trimmedResult);
    return trimmedResult;
  } catch (error) {
    console.error("Error interpreting death diagnosis:", error);
    return "Error: Unable to interpret diagnosis. The original diagnosis has been recorded.";
  }
};

export const analyzeDeathDiagnosisPatterns = async (
  deceasedPatients: Patient[]
): Promise<string> => {
  const diagnosisSummaries = deceasedPatients
    .filter(p => p.aiInterpretedDeathDiagnosis || p.diagnosisAtDeath)
    .slice(0, 50)
    .map(p => {
      const diagnosis = p.aiInterpretedDeathDiagnosis || p.diagnosisAtDeath || 'Unknown';
      const daysInUnit = p.dateOfDeath && p.admissionDate
        ? Math.ceil((new Date(p.dateOfDeath).getTime() - new Date(p.admissionDate).getTime()) / (1000 * 60 * 60 * 24))
        : 'unknown';
      return `- ${p.age} ${p.ageUnit}, ${p.unit}, ${daysInUnit} days in unit: ${diagnosis}`;
    })
    .join('\n');

  if (!diagnosisSummaries) {
    return "No death diagnosis data available for analysis.";
  }

  const prompt = `You are an expert pediatric intensivist and mortality review specialist with deep knowledge of NICU/PICU care patterns.

Analyze these death diagnoses from NICU/PICU patients and provide a comprehensive, actionable analysis.

Death Diagnosis Data (${deceasedPatients.length} deceased patients):
${diagnosisSummaries}

Provide a detailed, evidence-based analysis with the following structure:

## EXECUTIVE SUMMARY
- 2-3 sentence overview of key findings
- Most critical insight requiring immediate attention

## PRIMARY CAUSES OF DEATH
Rank the top 5-7 causes with:
- Specific diagnosis/condition
- Estimated percentage (%)
- Typical age group affected
- Common time to death (early vs late mortality)

## AGE-STRATIFIED ANALYSIS
Break down by age groups:
- **Neonates (0-28 days)**: Common causes, patterns
- **Infants (1-12 months)**: Common causes, patterns
- **Children (>1 year)**: Common causes, patterns

## UNIT-SPECIFIC PATTERNS
- **NICU mortality**: Dominant conditions, preventability assessment
- **PICU mortality**: Dominant conditions, preventability assessment
- Comparison and contrasts between units

## TEMPORAL PATTERNS
- Early deaths (<24 hours): What's driving these?
- Late deaths (>7 days): What conditions lead to prolonged ICU stays before death?
- Identify any critical windows

## POTENTIALLY PREVENTABLE DEATHS
- Which cases might have been preventable with earlier intervention?
- What specific gaps in care are suggested?
- Are there recurring themes?

## CLINICAL INSIGHTS
- Pathophysiology patterns across cases
- Co-morbidities contributing to mortality
- Treatment challenges identified

## QUALITY IMPROVEMENT RECOMMENDATIONS
Provide 5-7 specific, actionable recommendations:
1. **Protocol Changes**: What clinical protocols should be revised?
2. **Early Warning Systems**: What monitoring could catch deterioration earlier?
3. **Resource Allocation**: Where should resources be focused?
4. **Staff Training**: What specific competencies need strengthening?
5. **Equipment/Technology**: What could help prevent these deaths?
6. **Family Counseling**: How to better support families?
7. **Research Opportunities**: What needs further investigation?

## LEARNING POINTS
- Key clinical pearls from this data
- What should the team prioritize?

## SUCCESS METRICS
- How should improvements be measured?
- What KPIs should be tracked?

Use specific numbers from the data. Be direct, evidence-based, and actionable. Format with clear headers, bullet points, and bold text for emphasis.`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT, { maxTokens: 4000 });
    return result + "\n\n" + AI_DISCLAIMER;
  } catch (error) {
    console.error("Error analyzing death diagnosis patterns:", error);
    return "Unable to analyze death diagnosis patterns at this time.";
  }
};

/**
 * Analyze individual patient mortality
 */
export const analyzeIndividualMortality = async (patient: Patient): Promise<string> => {
  const daysInUnit = patient.dateOfDeath && patient.admissionDate
    ? Math.ceil((new Date(patient.dateOfDeath).getTime() - new Date(patient.admissionDate).getTime()) / (1000 * 60 * 60 * 24))
    : 'unknown';

  const recentNotes = patient.progressNotes
    .slice(-5)
    .map(n => `${new Date(n.date).toLocaleString()}: ${n.note || 'No note'}`)
    .join('\n');

  const prompt = `You are a pediatric mortality review specialist. Provide a concise clinical analysis.

**Patient Details:**
- Age: ${patient.age} ${patient.ageUnit}
- Unit: ${patient.unit}
- Days in unit: ${daysInUnit}
- Admission: ${new Date(patient.admissionDate).toLocaleDateString()}
- Death: ${patient.dateOfDeath ? `${new Date(patient.dateOfDeath).toLocaleDateString()} at ${new Date(patient.dateOfDeath).toLocaleTimeString()}` : 'Not recorded'}

**Diagnosis at Death:**
${patient.diagnosisAtDeath || 'Not recorded'}

**Recent Clinical Notes:**
${recentNotes || 'No notes available'}

Provide a brief clinical summary (3-4 concise paragraphs):

**Clinical Summary:**
Briefly describe the patient's presentation, clinical course, and cause of death.

**Key Findings:**
- Primary cause of death
- Contributing factors
- Critical events in the timeline

**Assessment:**
Brief note on preventability (Preventable/Potentially Preventable/Non-Preventable) with 1-2 sentence justification.

Keep the response professional, concise, and under 200 words total. No separate detailed sections needed.`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT);
    return result + "\n\n" + AI_DISCLAIMER;
  } catch (error) {
    console.error("Error analyzing individual mortality:", error);
    return "Unable to analyze individual mortality at this time.";
  }
};

// ============================================================================
// VOICE & CLINICAL NOTE AI
// ============================================================================

export const formatVoiceTranscript = async (
  transcript: string,
  noteType: 'progress' | 'admission' | 'discharge'
): Promise<string> => {
  const formatGuide = {
    progress: 'SOAP format (Subjective, Objective, Assessment, Plan)',
    admission: 'Admission note format (Chief Complaint, History, Examination, Plan)',
    discharge: 'Discharge summary format (Hospital Course, Diagnosis, Instructions, Follow-up)'
  };

  const prompt = `Convert this voice-dictated clinical note into a structured ${noteType} note.

Voice Transcript:
${transcript}

Format as: ${formatGuide[noteType]}

Clean up:
- Fix grammar and punctuation
- Expand medical abbreviations where helpful
- Organize information logically
- Keep clinical content accurate
- Remove filler words

Output the formatted clinical note only.`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT);
    return result;
  } catch (error) {
    console.error("Error formatting voice transcript:", error);
    return transcript; // Return original if formatting fails
  }
};

export const extractMedicationsFromNote = async (note: string): Promise<any[]> => {
  const prompt = `Extract all medications mentioned in this clinical note:

${note}

For each medication found, extract:
- name: medication name
- dose: dosage if mentioned
- route: route of administration if mentioned
- frequency: frequency if mentioned

Output as JSON array:
[{ "name": "...", "dose": "...", "route": "...", "frequency": "..." }]

If no medications found, return empty array: []`;

  try {
    const response = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT, { jsonMode: true });
    const cleaned = response.replace(/```json|```/g, '').trim();
    return JSON.parse(cleaned);
  } catch (error) {
    console.error("Error extracting medications:", error);
    return [];
  }
};

export const generateClinicalNoteFromTemplate = async (
  template: string,
  patientData: any,
  additionalContext?: string
): Promise<string> => {
  const prompt = `Generate a clinical note based on this template and patient data.

Template:
${template}

Patient Data:
${JSON.stringify(patientData, null, 2)}

${additionalContext ? `Additional Context: ${additionalContext}` : ''}

Fill in the template with appropriate clinical content based on the patient data.
Maintain professional medical documentation standards.
Keep responses concise and clinically relevant.`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT);
    return result;
  } catch (error) {
    console.error("Error generating clinical note:", error);
    return "Unable to generate clinical note at this time.";
  }
};

// ============================================================================
// DISCHARGE SUMMARY GENERATION
// ============================================================================

/**
 * Generate a comprehensive clinical course summary for discharge
 */
export const generateDischargeClinicalSummary = async (patient: Patient): Promise<string> => {
  const progressNotes = patient.progressNotes || [];

  // Format progress notes for AI
  const notesText = progressNotes.map((note, index) => {
    const date = new Date(note.date).toLocaleDateString('en-IN', {
      day: '2-digit', month: 'short', year: 'numeric'
    });

    let noteContent = `Day ${index + 1} (${date}):`;

    if (note.note) {
      noteContent += ` ${note.note}`;
    }

    if (note.vitals) {
      const vitals = Object.entries(note.vitals)
        .filter(([_, v]) => v)
        .map(([k, v]) => `${k}: ${v}`)
        .join(', ');
      if (vitals) noteContent += ` Vitals: ${vitals}.`;
    }

    if (note.examination) {
      const exam = Object.entries(note.examination)
        .filter(([_, v]) => v)
        .map(([k, v]) => `${k}: ${v}`)
        .join(', ');
      if (exam) noteContent += ` Examination: ${exam}.`;
    }

    if (note.medications && note.medications.length > 0) {
      const meds = note.medications.map(m => `${m.name} ${m.dose}`).join(', ');
      noteContent += ` Medications: ${meds}.`;
    }

    return noteContent;
  }).join('\n');

  // Calculate length of stay
  const admissionDate = new Date(patient.admissionDate);
  const dischargeDate = patient.releaseDate ? new Date(patient.releaseDate) : new Date();
  const stayDays = Math.ceil((dischargeDate.getTime() - admissionDate.getTime()) / (1000 * 60 * 60 * 24));

  const prompt = `You are a senior neonatologist/pediatric intensivist writing a discharge summary. Generate a comprehensive but concise CLINICAL COURSE SUMMARY based on the patient data below.

=== PATIENT INFORMATION ===
Name: ${patient.name}
Age: ${patient.age} ${patient.ageUnit}
Gender: ${patient.gender}
Unit: ${patient.unit}
Admission Date: ${new Date(patient.admissionDate).toLocaleDateString('en-IN')}
Length of Stay: ${stayDays} days
Primary Diagnosis: ${patient.diagnosis}
${patient.birthWeight ? `Birth Weight: ${patient.birthWeight} kg` : ''}
${patient.gestationalAgeWeeks ? `Gestational Age: ${patient.gestationalAgeWeeks} weeks ${patient.gestationalAgeDays || 0} days (${patient.gestationalAgeCategory || ''})` : ''}
${patient.modeOfDelivery ? `Mode of Delivery: ${patient.modeOfDelivery}` : ''}
${patient.indicationsForAdmission?.length ? `Indications for Admission: ${patient.indicationsForAdmission.join(', ')}` : ''}

=== MATERNAL HISTORY ===
${patient.maternalHistory ? `
Mother's Age: ${patient.maternalHistory.maternalAge || 'Unknown'}
Obstetric History: G${patient.maternalHistory.gravida || 0} P${patient.maternalHistory.para || 0} A${patient.maternalHistory.abortion || 0} L${patient.maternalHistory.living || 0}
ANC: ${patient.maternalHistory.ancReceived ? 'Yes' : 'No'}${patient.maternalHistory.ancVisits ? ` (${patient.maternalHistory.ancVisits} visits)` : ''}
Antenatal Steroids: ${patient.maternalHistory.antenatalSteroidsGiven ? 'Yes' : 'No'}
Risk Factors: ${patient.maternalHistory.riskFactors?.join(', ') || 'None documented'}
` : 'Not documented'}

=== PROGRESS NOTES ===
${notesText || 'No detailed progress notes available.'}

=== CURRENT MEDICATIONS ===
${(patient.medications || []).filter(m => m.isActive !== false).map(m => `- ${m.name} ${m.dose} ${m.route || ''} ${m.frequency || ''}`).join('\n') || 'None'}

=== INSTRUCTIONS ===
Write a professional clinical course summary for a discharge document. Include:
1. Brief admission summary (why admitted, initial condition)
2. Hospital course (key treatments, interventions, response to therapy)
3. Significant events or complications (if any)
4. Current status and reason for discharge

Guidelines:
- Write in paragraph form, not bullet points
- Be concise but comprehensive (4-6 sentences)
- Use professional medical language
- Focus on clinically relevant information
- Do NOT use markdown formatting, asterisks, or bullet points
- Write in third person (e.g., "The patient was admitted..." not "I admitted...")`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT, {
      temperature: 0.4,
      maxTokens: 800
    });
    return result;
  } catch (error) {
    console.error('Error generating discharge clinical summary:', error);
    return 'Clinical course summary could not be generated. Please enter manually.';
  }
};

/**
 * Generate discharge advice based on patient condition and diagnoses
 */
export const generateDischargeAdvice = async (
  patient: Patient,
  isNICU: boolean
): Promise<string[]> => {
  const prompt = `Generate specific discharge advice for this patient.

Patient: ${patient.name}
Age: ${patient.age} ${patient.ageUnit}
Unit: ${isNICU ? 'NICU/SNCU (Neonatal)' : 'PICU (Pediatric)'}
Diagnosis: ${patient.diagnosis}
${patient.birthWeight ? `Birth Weight: ${patient.birthWeight} kg` : ''}
${patient.gestationalAgeCategory ? `Gestational Category: ${patient.gestationalAgeCategory}` : ''}

Current Medications: ${(patient.medications || []).filter(m => m.isActive !== false).map(m => m.name).join(', ') || 'None'}

Generate 5-7 specific, actionable discharge advice points tailored to this patient's condition.
Format: Return ONLY a JSON array of strings, each being one advice point.
Example: ["Continue breastfeeding on demand", "Give medication X as prescribed", ...]

Important: Return ONLY the JSON array, no other text.`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT, {
      temperature: 0.3,
      maxTokens: 500,
      jsonMode: true
    });

    const parsed = JSON.parse(result);
    if (Array.isArray(parsed)) return parsed;
    if (parsed.advice && Array.isArray(parsed.advice)) return parsed.advice;

    return getDefaultDischargeAdvice(isNICU);
  } catch (error) {
    console.error('Error generating discharge advice:', error);
    return getDefaultDischargeAdvice(isNICU);
  }
};

function getDefaultDischargeAdvice(isNICU: boolean): string[] {
  if (isNICU) {
    return [
      'Continue breastfeeding on demand or as per feeding schedule advised',
      'Practice Kangaroo Mother Care (skin-to-skin contact) for at least 1 hour twice daily',
      'Keep baby warm - maintain room temperature around 25-28°C',
      'Wash hands thoroughly before handling baby',
      'Give all medications as prescribed',
      'Complete immunization schedule as advised',
      'Follow up on the scheduled date'
    ];
  } else {
    return [
      'Continue medications as prescribed',
      'Ensure adequate nutrition and hydration',
      'Allow gradual return to normal activities',
      'Watch for any warning signs and report immediately',
      'Complete the prescribed course of medications',
      'Follow up with the treating doctor as scheduled'
    ];
  }
}

/**
 * Generate warning signs to watch based on diagnosis
 */
export const generateWarningSignsForDischarge = async (
  patient: Patient,
  isNICU: boolean
): Promise<string[]> => {
  const prompt = `Generate warning signs for parents/caregivers to watch after discharge.

Patient: ${patient.name}
Age: ${patient.age} ${patient.ageUnit}
Unit: ${isNICU ? 'NICU/SNCU (Neonatal)' : 'PICU (Pediatric)'}
Diagnosis: ${patient.diagnosis}
${patient.gestationalAgeCategory ? `Gestational Category: ${patient.gestationalAgeCategory}` : ''}

Generate 6-8 specific warning signs that should prompt immediate medical attention.
These should be tailored to the patient's diagnosis and age.

Format: Return ONLY a JSON array of strings.
Example: ["High fever (>100.4°F/38°C)", "Difficulty breathing", ...]

Return ONLY the JSON array.`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT, {
      temperature: 0.3,
      maxTokens: 400,
      jsonMode: true
    });

    const parsed = JSON.parse(result);
    if (Array.isArray(parsed)) return parsed;
    if (parsed.signs && Array.isArray(parsed.signs)) return parsed.signs;

    return getDefaultWarnings(isNICU);
  } catch (error) {
    console.error('Error generating warning signs:', error);
    return getDefaultWarnings(isNICU);
  }
};

function getDefaultWarnings(isNICU: boolean): string[] {
  if (isNICU) {
    return [
      'Difficulty breathing or fast breathing (>60/min)',
      'Not feeding well or refusing to feed',
      'High fever (>100.4°F / 38°C) or very cold baby',
      'Yellow discoloration of skin or eyes (jaundice)',
      'Excessive sleepiness or difficulty waking for feeds',
      'Convulsions or abnormal movements',
      'Umbilical cord redness, swelling, or foul discharge',
      'Skin rash, pustules, or blisters'
    ];
  } else {
    return [
      'High fever that does not respond to medication',
      'Difficulty breathing or rapid breathing',
      'Persistent vomiting or inability to keep fluids down',
      'Signs of dehydration (dry mouth, no tears, reduced urination)',
      'Unusual drowsiness or confusion',
      'Seizures or convulsions',
      'Severe abdominal pain',
      'Rash that does not fade with pressure'
    ];
  }
}

/**
 * Generate final diagnosis for discharge based on clinical course analysis
 * Uses accurate ICD-10 aligned medical terminology
 * Format: Concise, standard medical discharge diagnosis
 */
export const generateFinalDiagnosis = async (patient: Patient): Promise<string> => {
  const progressNotes = patient.progressNotes || [];

  // Format progress notes for AI (brief)
  const notesText = progressNotes.slice(-5).map((note, index) => {
    let content = `Day ${index + 1}:`;
    if (note.note) content += ` ${note.note.substring(0, 200)}`;
    return content;
  }).join(' | ');

  // Determine gestational age string with proper format
  let gaString = '';
  let pretermCategory = '';
  if (patient.gestationalAgeWeeks !== undefined) {
    const weeks = patient.gestationalAgeWeeks;
    const days = patient.gestationalAgeDays || 0;
    gaString = days > 0 ? `${weeks}+${days} weeks` : `${weeks} weeks`;

    if (weeks < 28) pretermCategory = 'Extreme preterm';
    else if (weeks < 32) pretermCategory = 'Very preterm';
    else if (weeks < 34) pretermCategory = 'Moderate preterm';
    else if (weeks < 37) pretermCategory = 'Late preterm';
  }

  // Determine weight category with proper terminology
  let weightCategory = '';
  if (patient.birthWeight !== undefined) {
    const wt = patient.birthWeight;
    if (wt < 1) weightCategory = 'ELBW';
    else if (wt < 1.5) weightCategory = 'VLBW';
    else if (wt < 2.5) weightCategory = 'LBW';
    else if (wt >= 4) weightCategory = 'LGA';
  }

  // Check for SGA/AGA/LGA based on gestational age and weight
  let growthStatus = '';
  if (patient.gestationalAgeWeeks && patient.birthWeight) {
    // Simplified check - can be enhanced with growth charts
    const expectedWeight = patient.gestationalAgeWeeks * 0.1; // Rough estimate
    if (patient.birthWeight < expectedWeight * 0.8) growthStatus = 'SGA';
  }

  const prompt = `You are a neonatologist writing a FINAL DIAGNOSIS for discharge. Generate an ACCURATE, CONCISE diagnosis.

=== PATIENT DATA ===
Unit: ${patient.unit}
Gestational Age: ${gaString || 'Term (≥37 weeks)'}
${pretermCategory ? `Preterm Category: ${pretermCategory}` : ''}
Birth Weight: ${patient.birthWeight ? `${patient.birthWeight} kg` : 'Unknown'}
${weightCategory ? `Weight Category: ${weightCategory}` : ''}
${growthStatus ? `Growth Status: ${growthStatus}` : ''}
Gender: ${patient.gender}

Admission Diagnosis: ${patient.diagnosis}
Indications for Admission: ${patient.indicationsForAdmission?.join(', ') || 'Not specified'}

Medications Given: ${(patient.medications || []).map(m => m.name).join(', ') || 'None'}

Clinical Notes: ${notesText || 'None documented'}

=== STANDARD NEONATAL DIAGNOSES (ICD-10 aligned) ===
PREMATURITY:
- Preterm infant, [GA] weeks gestation
- Extreme prematurity (<28 weeks)
- Very preterm (28-31 weeks)
- Moderate to late preterm (32-36 weeks)

BIRTH WEIGHT:
- ELBW - Extremely Low Birth Weight (<1000g)
- VLBW - Very Low Birth Weight (1000-1499g)
- LBW - Low Birth Weight (1500-2499g)
- SGA - Small for Gestational Age
- AGA - Appropriate for Gestational Age

RESPIRATORY:
- Respiratory Distress Syndrome (RDS) / Hyaline Membrane Disease
- Transient Tachypnea of Newborn (TTN)
- Meconium Aspiration Syndrome (MAS)
- Bronchopulmonary Dysplasia (BPD)
- Apnea of Prematurity

INFECTIONS:
- Neonatal Sepsis (Early-onset / Late-onset)
- Suspected Sepsis
- Pneumonia

METABOLIC/OTHER:
- Neonatal Hyperbilirubinemia / Neonatal Jaundice
- Hypoglycemia
- Perinatal Asphyxia / Birth Asphyxia
- Hypoxic Ischemic Encephalopathy (HIE)
- Neonatal Seizures
- Anemia of Prematurity
- Feeding Intolerance

=== OUTPUT FORMAT ===
Write diagnosis in this EXACT format:
[Preterm/Term status], [Weight category if abnormal], [Primary Diagnosis] - [Status], [Secondary if any] - [Status]

STATUS OPTIONS: Recovered, Resolved, Treated, Stable, Improving

=== EXAMPLES OF CORRECT OUTPUT ===
1. "Preterm (32+4 weeks), VLBW, Respiratory Distress Syndrome - Recovered, Neonatal Sepsis - Treated"
2. "Late preterm (35 weeks), LBW, Neonatal Hyperbilirubinemia - Resolved"
3. "Extreme preterm (26 weeks), ELBW, RDS - Recovered, Apnea of Prematurity - Resolved, Sepsis - Treated"
4. "Term, Meconium Aspiration Syndrome - Recovered"
5. "Very preterm (30 weeks), VLBW, SGA, Suspected Sepsis - Treated, Hypoglycemia - Resolved"
6. "Term, Birth Asphyxia with HIE Stage 1 - Recovered"

=== RULES ===
1. Be ACCURATE - use correct medical terminology
2. Include gestational age in parentheses for preterm
3. List weight category only if abnormal (ELBW/VLBW/LBW/SGA)
4. Use full diagnosis names (can abbreviate RDS, HIE, TTN, MAS, BPD)
5. Add outcome status for each diagnosis
6. Keep it ONE LINE, concise but complete
7. NO explanations, just the diagnosis`;

  try {
    const result = await callOpenAI(prompt, MEDICAL_SYSTEM_PROMPT, {
      temperature: 0.2,
      maxTokens: 150
    });

    // Clean up the result
    let diagnosis = result.trim()
      .replace(/^["']|["']$/g, '') // Remove quotes
      .replace(/\n.*/g, '') // Keep only first line
      .replace(/^(Final )?[Dd]iagnosis:?\s*/i, '') // Remove "Diagnosis:" prefix
      .replace(/^\d+\.\s*/, ''); // Remove numbering if present

    return diagnosis || patient.diagnosis;
  } catch (error) {
    console.error('Error generating final diagnosis:', error);
    // Return an accurate fallback diagnosis
    const parts = [];

    if (patient.gestationalAgeWeeks && patient.gestationalAgeWeeks < 37) {
      const weeks = patient.gestationalAgeWeeks;
      const days = patient.gestationalAgeDays || 0;
      const gaStr = days > 0 ? `${weeks}+${days} weeks` : `${weeks} weeks`;
      if (weeks < 32) parts.push(`Very preterm (${gaStr})`);
      else if (weeks < 34) parts.push(`Moderate preterm (${gaStr})`);
      else parts.push(`Late preterm (${gaStr})`);
    } else {
      parts.push('Term');
    }

    if (weightCategory) {
      parts.push(weightCategory);
    }

    // Add the primary diagnosis
    parts.push(patient.diagnosis);

    return parts.join(', ');
  }
};

// ============================================================================
// UTILITY EXPORTS
// ============================================================================

export const clearAICache = () => {
  aiCache.clear();
  console.log('AI cache cleared');
};

export const getAICacheStats = () => {
  return {
    size: aiCache.size,
    entries: Array.from(aiCache.keys())
  };
};

// Export the raw callOpenAI for other services that need it
export { callOpenAI };
