import { collection, addDoc } from 'firebase/firestore';
import { db } from '../firebaseConfig';
import { MedicationDatabase, MedicationCategory, Unit } from '../types';

const COMMON_NICU_PICU_MEDICATIONS: Omit<MedicationDatabase, 'id' | 'createdAt' | 'createdBy'>[] = [
  // ANTIBIOTICS
  {
    name: 'Ampicillin',
    brandNames: ['Omnipen', 'Principen'],
    category: MedicationCategory.Antibiotic,
    commonDoses: ['50mg/kg', '100mg/kg', '200mg/kg'],
    routes: ['IV', 'IM'],
    frequencies: ['BD', 'TID', 'QID'],
    indication: 'Bacterial infections, neonatal sepsis, meningitis, GBS prophylaxis',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Preterm', 'Infant', 'Child'],
    warnings: 'Adjust dose in renal impairment. Monitor for hypersensitivity reactions.',
    searchTerms: ['abx', 'antibiotic', 'penicillin'],
    isActive: true,
  },
  {
    name: 'Gentamicin',
    brandNames: ['Garamycin'],
    category: MedicationCategory.Antibiotic,
    commonDoses: ['4mg/kg', '5mg/kg', '7.5mg/kg'],
    routes: ['IV', 'IM'],
    frequencies: ['OD', 'Once daily'],
    indication: 'Gram-negative bacterial infections, neonatal sepsis',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Preterm', 'Infant'],
    warnings: 'Nephrotoxic and ototoxic. Monitor renal function and drug levels. Avoid in renal failure.',
    searchTerms: ['abx', 'aminoglycoside'],
    isActive: true,
  },
  {
    name: 'Cefotaxime',
    brandNames: ['Claforan'],
    category: MedicationCategory.Antibiotic,
    commonDoses: ['50mg/kg', '100mg/kg', '150mg/kg'],
    routes: ['IV', 'IM'],
    frequencies: ['BD', 'TID'],
    indication: 'Gram-positive and gram-negative bacterial infections, meningitis',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Preterm', 'Infant', 'Child'],
    warnings: 'Third-generation cephalosporin. Monitor for C. diff infection.',
    searchTerms: ['abx', 'cephalosporin', 'cef'],
    isActive: true,
  },
  {
    name: 'Amikacin',
    brandNames: ['Amikin'],
    category: MedicationCategory.Antibiotic,
    commonDoses: ['15mg/kg', '20mg/kg'],
    routes: ['IV', 'IM'],
    frequencies: ['OD', 'Once daily'],
    indication: 'Gram-negative infections resistant to gentamicin',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Preterm', 'Infant', 'Child'],
    warnings: 'Nephrotoxic and ototoxic. Monitor levels and renal function.',
    searchTerms: ['abx', 'aminoglycoside'],
    isActive: true,
  },
  {
    name: 'Meropenem',
    brandNames: ['Merrem'],
    category: MedicationCategory.Antibiotic,
    commonDoses: ['20mg/kg', '40mg/kg'],
    routes: ['IV'],
    frequencies: ['TID', 'Q8H'],
    indication: 'Severe bacterial infections, meningitis, resistant infections',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Infant', 'Child'],
    warnings: 'Carbapenem antibiotic. Risk of seizures at high doses.',
    searchTerms: ['abx', 'carbapenem', 'broad spectrum'],
    isActive: true,
  },
  {
    name: 'Vancomycin',
    brandNames: ['Vancocin'],
    category: MedicationCategory.Antibiotic,
    commonDoses: ['10mg/kg', '15mg/kg', '20mg/kg'],
    routes: ['IV'],
    frequencies: ['BD', 'TID', 'QID'],
    indication: 'MRSA, gram-positive bacterial infections, coagulase-negative staph',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Preterm', 'Infant', 'Child'],
    warnings: 'Nephrotoxic and ototoxic. Monitor trough levels. Infuse slowly to avoid red man syndrome.',
    searchTerms: ['abx', 'glycopeptide', 'mrsa'],
    isActive: true,
  },
  {
    name: 'Metronidazole',
    brandNames: ['Flagyl'],
    category: MedicationCategory.Antibiotic,
    commonDoses: ['7.5mg/kg', '15mg/kg'],
    routes: ['IV', 'PO'],
    frequencies: ['BD', 'TID'],
    indication: 'Anaerobic bacterial infections, NEC, intra-abdominal infections',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Infant', 'Child'],
    warnings: 'Avoid in first trimester of pregnancy. Monitor for CNS toxicity.',
    searchTerms: ['abx', 'anaerobic'],
    isActive: true,
  },
  {
    name: 'Piperacillin-Tazobactam',
    brandNames: ['Tazocin', 'Zosyn'],
    category: MedicationCategory.Antibiotic,
    commonDoses: ['80mg/kg', '100mg/kg'],
    routes: ['IV'],
    frequencies: ['TID', 'Q6H'],
    indication: 'Broad-spectrum coverage, sepsis, pneumonia',
    applicableUnits: [Unit.PICU, Unit.HDU, Unit.NICU],
    ageGroups: ['Infant', 'Child'],
    warnings: 'Beta-lactam antibiotic. Monitor for allergic reactions.',
    searchTerms: ['abx', 'pip-tazo', 'broad spectrum'],
    isActive: true,
  },
  {
    name: 'Ceftriaxone',
    brandNames: ['Rocephin'],
    category: MedicationCategory.Antibiotic,
    commonDoses: ['50mg/kg', '75mg/kg', '100mg/kg'],
    routes: ['IV', 'IM'],
    frequencies: ['OD', 'Once daily'],
    indication: 'Bacterial meningitis, sepsis, pneumonia',
    applicableUnits: [Unit.PICU, Unit.HDU, Unit.SNCU],
    ageGroups: ['Infant', 'Child'],
    warnings: 'Avoid in neonates with hyperbilirubinemia (displaces bilirubin). Do not mix with calcium.',
    searchTerms: ['abx', 'cephalosporin', 'cef'],
    isActive: true,
  },
  {
    name: 'Ciprofloxacin',
    brandNames: ['Cipro'],
    category: MedicationCategory.Antibiotic,
    commonDoses: ['10mg/kg', '15mg/kg'],
    routes: ['IV', 'PO'],
    frequencies: ['BD'],
    indication: 'Gram-negative infections, UTI, pseudomonas',
    applicableUnits: [Unit.PICU, Unit.HDU],
    ageGroups: ['Child'],
    warnings: 'Fluoroquinolone. Avoid in young children due to cartilage toxicity concerns.',
    searchTerms: ['abx', 'fluoroquinolone'],
    isActive: true,
  },

  // RESPIRATORY SUPPORT
  {
    name: 'Caffeine Citrate',
    brandNames: ['Cafcit'],
    category: MedicationCategory.Respiratory,
    commonDoses: ['20mg/kg loading', '5mg/kg maintenance', '10mg/kg maintenance'],
    routes: ['IV', 'PO'],
    frequencies: ['OD', 'Once daily'],
    indication: 'Apnea of prematurity, respiratory support in preterm neonates',
    applicableUnits: [Unit.NICU, Unit.SNCU],
    ageGroups: ['Preterm', 'Newborn'],
    warnings: 'Monitor heart rate and feeding tolerance. Tachycardia may occur.',
    searchTerms: ['apnea', 'respiratory', 'preterm'],
    isActive: true,
  },
  {
    name: 'Surfactant (Poractant alfa)',
    brandNames: ['Curosurf'],
    category: MedicationCategory.Surfactant,
    commonDoses: ['100mg/kg', '200mg/kg'],
    routes: ['Endotracheal'],
    frequencies: ['Single dose', 'May repeat'],
    indication: 'Respiratory distress syndrome (RDS), surfactant deficiency',
    applicableUnits: [Unit.NICU, Unit.SNCU],
    ageGroups: ['Preterm', 'Newborn'],
    warnings: 'Administer via endotracheal tube. Monitor oxygen saturation closely.',
    searchTerms: ['rds', 'respiratory', 'lung'],
    isActive: true,
  },
  {
    name: 'Surfactant (Beractant)',
    brandNames: ['Survanta'],
    category: MedicationCategory.Surfactant,
    commonDoses: ['100mg/kg'],
    routes: ['Endotracheal'],
    frequencies: ['Q6H prn', 'Up to 4 doses'],
    indication: 'Respiratory distress syndrome (RDS)',
    applicableUnits: [Unit.NICU, Unit.SNCU],
    ageGroups: ['Preterm', 'Newborn'],
    warnings: 'Natural bovine surfactant. Monitor respiratory status.',
    searchTerms: ['rds', 'respiratory', 'lung'],
    isActive: true,
  },
  {
    name: 'Aminophylline',
    brandNames: [],
    category: MedicationCategory.Respiratory,
    commonDoses: ['5mg/kg loading', '2mg/kg maintenance'],
    routes: ['IV'],
    frequencies: ['BD', 'TID'],
    indication: 'Apnea of prematurity, bronchodilation',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU],
    ageGroups: ['Preterm', 'Newborn', 'Infant'],
    warnings: 'Monitor theophylline levels. Risk of seizures and arrhythmias.',
    searchTerms: ['apnea', 'respiratory', 'bronchodilator'],
    isActive: true,
  },
  {
    name: 'Salbutamol',
    brandNames: ['Ventolin', 'Albuterol'],
    category: MedicationCategory.Respiratory,
    commonDoses: ['2.5mg nebulization', '5mg nebulization'],
    routes: ['Nebulization', 'Inhalation'],
    frequencies: ['QID', 'Q4H prn'],
    indication: 'Bronchospasm, asthma, bronchiolitis',
    applicableUnits: [Unit.PICU, Unit.HDU, Unit.GENERAL_WARD],
    ageGroups: ['Infant', 'Child'],
    warnings: 'Beta-2 agonist. Monitor for tachycardia and tremors.',
    searchTerms: ['bronchodilator', 'asthma', 'wheeze'],
    isActive: true,
  },
  {
    name: 'Ipratropium Bromide',
    brandNames: ['Atrovent'],
    category: MedicationCategory.Respiratory,
    commonDoses: ['250mcg nebulization', '500mcg nebulization'],
    routes: ['Nebulization'],
    frequencies: ['QID', 'Q4H prn'],
    indication: 'Bronchospasm, asthma, COPD',
    applicableUnits: [Unit.PICU, Unit.HDU],
    ageGroups: ['Infant', 'Child'],
    warnings: 'Anticholinergic. Avoid in glaucoma.',
    searchTerms: ['bronchodilator', 'asthma'],
    isActive: true,
  },

  // CARDIOVASCULAR MEDICATIONS
  {
    name: 'Dopamine',
    brandNames: [],
    category: MedicationCategory.Inotrope,
    commonDoses: ['5mcg/kg/min', '10mcg/kg/min', '15mcg/kg/min', '20mcg/kg/min'],
    routes: ['IV infusion'],
    frequencies: ['Continuous'],
    indication: 'Hypotension, cardiogenic shock, inotropic support',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Preterm', 'Infant', 'Child'],
    warnings: 'Requires central line. Monitor BP continuously. Extravasation causes tissue necrosis.',
    searchTerms: ['inotrope', 'shock', 'bp support', 'vasopressor'],
    isActive: true,
  },
  {
    name: 'Dobutamine',
    brandNames: [],
    category: MedicationCategory.Inotrope,
    commonDoses: ['5mcg/kg/min', '10mcg/kg/min', '15mcg/kg/min', '20mcg/kg/min'],
    routes: ['IV infusion'],
    frequencies: ['Continuous'],
    indication: 'Cardiogenic shock, low cardiac output, heart failure',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Preterm', 'Infant', 'Child'],
    warnings: 'Beta-1 agonist. Monitor heart rate and BP. May cause tachycardia.',
    searchTerms: ['inotrope', 'cardiac', 'heart failure'],
    isActive: true,
  },
  {
    name: 'Epinephrine (Adrenaline)',
    brandNames: ['Adrenaline'],
    category: MedicationCategory.Inotrope,
    commonDoses: ['0.1mcg/kg/min', '0.3mcg/kg/min', '0.5mcg/kg/min', '0.01mg/kg (resuscitation)'],
    routes: ['IV infusion', 'IV bolus', 'IM'],
    frequencies: ['Continuous', 'PRN for resuscitation'],
    indication: 'Cardiac arrest, anaphylaxis, severe hypotension, bradycardia',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Preterm', 'Infant', 'Child'],
    warnings: 'Potent vasoconstrictor. Monitor for arrhythmias. Extravasation causes necrosis.',
    searchTerms: ['inotrope', 'resuscitation', 'code', 'arrest', 'anaphylaxis'],
    isActive: true,
  },
  {
    name: 'Norepinephrine (Noradrenaline)',
    brandNames: ['Levophed'],
    category: MedicationCategory.Inotrope,
    commonDoses: ['0.05mcg/kg/min', '0.1mcg/kg/min', '0.5mcg/kg/min', '1mcg/kg/min'],
    routes: ['IV infusion'],
    frequencies: ['Continuous'],
    indication: 'Septic shock, severe hypotension, distributive shock',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Infant', 'Child'],
    warnings: 'Requires central line. Potent vasoconstrictor. Monitor BP continuously.',
    searchTerms: ['inotrope', 'vasopressor', 'shock', 'sepsis'],
    isActive: true,
  },
  {
    name: 'Milrinone',
    brandNames: ['Primacor'],
    category: MedicationCategory.Inotrope,
    commonDoses: ['0.25mcg/kg/min', '0.5mcg/kg/min', '0.75mcg/kg/min'],
    routes: ['IV infusion'],
    frequencies: ['Continuous'],
    indication: 'Heart failure, post-cardiac surgery, pulmonary hypertension',
    applicableUnits: [Unit.PICU, Unit.HDU, Unit.NICU],
    ageGroups: ['Newborn', 'Infant', 'Child'],
    warnings: 'Phosphodiesterase inhibitor. Monitor BP and heart rate. May cause hypotension.',
    searchTerms: ['inotrope', 'cardiac', 'heart failure', 'pulmonary hypertension'],
    isActive: true,
  },
  {
    name: 'Prostaglandin E1 (Alprostadil)',
    brandNames: ['Prostin VR'],
    category: MedicationCategory.Cardiovascular,
    commonDoses: ['0.01mcg/kg/min', '0.05mcg/kg/min', '0.1mcg/kg/min'],
    routes: ['IV infusion'],
    frequencies: ['Continuous'],
    indication: 'Duct-dependent congenital heart disease, maintain patent ductus arteriosus',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU],
    ageGroups: ['Newborn', 'Infant'],
    warnings: 'Causes apnea - have intubation ready. Monitor for fever and hypotension.',
    searchTerms: ['pge1', 'cardiac', 'chd', 'duct-dependent'],
    isActive: true,
  },

  // ANALGESICS & SEDATIVES
  {
    name: 'Fentanyl',
    brandNames: ['Sublimaze'],
    category: MedicationCategory.Sedative,
    commonDoses: ['1mcg/kg', '2mcg/kg', '3mcg/kg', '1-3mcg/kg/hr infusion'],
    routes: ['IV', 'IV infusion'],
    frequencies: ['PRN', 'Q2H', 'Continuous'],
    indication: 'Pain management, sedation, ventilator tolerance',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Preterm', 'Infant', 'Child'],
    warnings: 'Opioid analgesic. Risk of respiratory depression. Monitor closely. Have naloxone available.',
    searchTerms: ['pain', 'sedation', 'analgesic', 'opioid'],
    isActive: true,
  },
  {
    name: 'Morphine',
    brandNames: [],
    category: MedicationCategory.Sedative,
    commonDoses: ['0.05mg/kg', '0.1mg/kg', '0.2mg/kg', '10-30mcg/kg/hr infusion'],
    routes: ['IV', 'IM', 'PO', 'IV infusion'],
    frequencies: ['PRN', 'Q4H', 'Continuous'],
    indication: 'Pain management, sedation, post-operative analgesia',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU, Unit.GENERAL_WARD],
    ageGroups: ['Newborn', 'Infant', 'Child'],
    warnings: 'Opioid. Respiratory depression. Monitor oxygen saturation. Have naloxone ready.',
    searchTerms: ['pain', 'analgesic', 'opioid', 'sedation'],
    isActive: true,
  },
  {
    name: 'Paracetamol (Acetaminophen)',
    brandNames: ['Tylenol', 'Crocin', 'Calpol'],
    category: MedicationCategory.Antipyretic,
    commonDoses: ['10mg/kg', '15mg/kg', '20mg/kg loading'],
    routes: ['PO', 'IV', 'PR'],
    frequencies: ['QID', 'Q6H', 'Q4H prn'],
    indication: 'Fever, mild to moderate pain',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU, Unit.GENERAL_WARD],
    ageGroups: ['Newborn', 'Infant', 'Child'],
    warnings: 'Hepatotoxic in overdose. Do not exceed maximum daily dose (75mg/kg/day for neonates, 90mg/kg/day for children).',
    searchTerms: ['fever', 'pain', 'antipyretic', 'tylenol'],
    isActive: true,
  },
  {
    name: 'Ibuprofen',
    brandNames: ['Brufen', 'Advil', 'Motrin'],
    category: MedicationCategory.Analgesic,
    commonDoses: ['5mg/kg', '10mg/kg'],
    routes: ['PO'],
    frequencies: ['TID', 'Q6H prn'],
    indication: 'Fever, pain, inflammation, PDA closure',
    applicableUnits: [Unit.PICU, Unit.HDU, Unit.GENERAL_WARD, Unit.NICU],
    ageGroups: ['Infant', 'Child'],
    warnings: 'NSAID. Avoid in renal impairment, bleeding disorders, active GI bleed.',
    searchTerms: ['fever', 'pain', 'antipyretic', 'nsaid'],
    isActive: true,
  },
  {
    name: 'Midazolam',
    brandNames: ['Versed'],
    category: MedicationCategory.Sedative,
    commonDoses: ['0.05mg/kg', '0.1mg/kg', '0.2mg/kg', '1-4mcg/kg/min infusion'],
    routes: ['IV', 'IM', 'PO', 'Intranasal', 'IV infusion'],
    frequencies: ['PRN', 'Q2H', 'Continuous'],
    indication: 'Sedation, seizures, procedural sedation, ventilator tolerance',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Infant', 'Child'],
    warnings: 'Benzodiazepine. Respiratory depression. Have flumazenil available as reversal agent.',
    searchTerms: ['sedation', 'seizure', 'benzo', 'anxiety'],
    isActive: true,
  },

  // ANTICONVULSANTS
  {
    name: 'Phenobarbital',
    brandNames: ['Luminal'],
    category: MedicationCategory.Anticonvulsant,
    commonDoses: ['20mg/kg loading', '5mg/kg maintenance'],
    routes: ['IV', 'PO'],
    frequencies: ['Loading then OD/BD'],
    indication: 'Neonatal seizures, status epilepticus',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Preterm', 'Infant', 'Child'],
    warnings: 'Barbiturate. Respiratory depression. Monitor drug levels. Sedation common.',
    searchTerms: ['seizure', 'anticonvulsant', 'epilepsy'],
    isActive: true,
  },
  {
    name: 'Phenytoin',
    brandNames: ['Dilantin'],
    category: MedicationCategory.Anticonvulsant,
    commonDoses: ['15-20mg/kg loading', '5mg/kg maintenance'],
    routes: ['IV', 'PO'],
    frequencies: ['Loading then BD/TID'],
    indication: 'Seizures, status epilepticus',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Infant', 'Child'],
    warnings: 'Monitor drug levels. Cardiac arrhythmias with rapid IV infusion. Avoid IM route.',
    searchTerms: ['seizure', 'anticonvulsant', 'epilepsy'],
    isActive: true,
  },
  {
    name: 'Levetiracetam',
    brandNames: ['Keppra'],
    category: MedicationCategory.Anticonvulsant,
    commonDoses: ['20mg/kg', '30mg/kg', '40mg/kg'],
    routes: ['IV', 'PO'],
    frequencies: ['BD'],
    indication: 'Seizures, neonatal seizures, status epilepticus',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Infant', 'Child'],
    warnings: 'Well-tolerated. No significant drug interactions. Behavioral changes possible.',
    searchTerms: ['seizure', 'anticonvulsant', 'epilepsy', 'keppra'],
    isActive: true,
  },
  {
    name: 'Diazepam',
    brandNames: ['Valium'],
    category: MedicationCategory.Anticonvulsant,
    commonDoses: ['0.2mg/kg', '0.3mg/kg', '0.5mg/kg'],
    routes: ['IV', 'PR', 'PO'],
    frequencies: ['PRN for seizures'],
    indication: 'Status epilepticus, acute seizures, muscle spasm',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU, Unit.GENERAL_WARD],
    ageGroups: ['Newborn', 'Infant', 'Child'],
    warnings: 'Benzodiazepine. Respiratory depression. Rectal route useful for status epilepticus.',
    searchTerms: ['seizure', 'anticonvulsant', 'benzo', 'status'],
    isActive: true,
  },

  // DIURETICS
  {
    name: 'Furosemide',
    brandNames: ['Lasix'],
    category: MedicationCategory.Diuretic,
    commonDoses: ['1mg/kg', '2mg/kg', '3mg/kg'],
    routes: ['IV', 'PO'],
    frequencies: ['OD', 'BD', 'PRN'],
    indication: 'Fluid overload, pulmonary edema, BPD, heart failure',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Preterm', 'Infant', 'Child'],
    warnings: 'Loop diuretic. Monitor electrolytes (hypokalemia). May cause ototoxicity at high doses.',
    searchTerms: ['diuretic', 'fluid', 'edema', 'lasix'],
    isActive: true,
  },
  {
    name: 'Spironolactone',
    brandNames: ['Aldactone'],
    category: MedicationCategory.Diuretic,
    commonDoses: ['1mg/kg', '2mg/kg', '3mg/kg'],
    routes: ['PO'],
    frequencies: ['OD', 'BD'],
    indication: 'Chronic lung disease, heart failure, potassium-sparing diuretic',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU],
    ageGroups: ['Newborn', 'Infant', 'Child'],
    warnings: 'Potassium-sparing diuretic. Monitor for hyperkalemia. Avoid in renal failure.',
    searchTerms: ['diuretic', 'fluid', 'potassium-sparing'],
    isActive: true,
  },

  // STEROIDS
  {
    name: 'Dexamethasone',
    brandNames: ['Decadron'],
    category: MedicationCategory.Steroid,
    commonDoses: ['0.15mg/kg', '0.5mg/kg', '0.6mg/kg'],
    routes: ['IV', 'PO'],
    frequencies: ['BD', 'OD'],
    indication: 'Bronchopulmonary dysplasia, airway edema, cerebral edema, croup',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Preterm', 'Infant', 'Child'],
    warnings: 'Corticosteroid. Hyperglycemia, hypertension, immunosuppression. GI bleed risk.',
    searchTerms: ['steroid', 'corticosteroid', 'anti-inflammatory', 'bpd'],
    isActive: true,
  },
  {
    name: 'Hydrocortisone',
    brandNames: ['Solu-Cortef'],
    category: MedicationCategory.Steroid,
    commonDoses: ['1mg/kg', '2mg/kg', '5mg/kg', '10mg/kg'],
    routes: ['IV', 'PO'],
    frequencies: ['TID', 'QID'],
    indication: 'Adrenal insufficiency, shock, sepsis, inflammatory conditions',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Preterm', 'Infant', 'Child'],
    warnings: 'Corticosteroid. Monitor blood glucose. Stress dose steroids in critical illness.',
    searchTerms: ['steroid', 'adrenal', 'shock', 'sepsis'],
    isActive: true,
  },
  {
    name: 'Methylprednisolone',
    brandNames: ['Solu-Medrol'],
    category: MedicationCategory.Steroid,
    commonDoses: ['1mg/kg', '2mg/kg', '30mg/kg pulse'],
    routes: ['IV', 'PO'],
    frequencies: ['OD', 'BD', 'Pulse therapy'],
    indication: 'Severe inflammation, asthma exacerbation, spinal cord injury',
    applicableUnits: [Unit.PICU, Unit.HDU],
    ageGroups: ['Child'],
    warnings: 'High-dose steroid. Monitor for hyperglycemia, hypertension, GI bleeding.',
    searchTerms: ['steroid', 'anti-inflammatory', 'asthma'],
    isActive: true,
  },

  // GASTROINTESTINAL
  {
    name: 'Ranitidine',
    brandNames: ['Zantac'],
    category: MedicationCategory.Gastrointestinal,
    commonDoses: ['2mg/kg', '3mg/kg'],
    routes: ['IV', 'PO'],
    frequencies: ['BD', 'TID'],
    indication: 'GERD, stress ulcer prophylaxis, acid suppression',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Infant', 'Child'],
    warnings: 'H2 blocker. May mask symptoms of GI bleeding. Adjust in renal impairment.',
    searchTerms: ['gerd', 'acid', 'ulcer', 'reflux'],
    isActive: true,
  },
  {
    name: 'Omeprazole',
    brandNames: ['Prilosec'],
    category: MedicationCategory.Gastrointestinal,
    commonDoses: ['0.7mg/kg', '1mg/kg', '2mg/kg'],
    routes: ['PO', 'IV'],
    frequencies: ['OD', 'BD'],
    indication: 'GERD, peptic ulcer, acid suppression',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Infant', 'Child'],
    warnings: 'Proton pump inhibitor. Long-term use increases infection risk. May cause hypomagnesemia.',
    searchTerms: ['gerd', 'ppi', 'acid', 'ulcer'],
    isActive: true,
  },
  {
    name: 'Ondansetron',
    brandNames: ['Zofran'],
    category: MedicationCategory.Gastrointestinal,
    commonDoses: ['0.1mg/kg', '0.15mg/kg'],
    routes: ['IV', 'PO'],
    frequencies: ['TID', 'Q8H prn'],
    indication: 'Nausea, vomiting, post-operative nausea',
    applicableUnits: [Unit.PICU, Unit.HDU, Unit.GENERAL_WARD],
    ageGroups: ['Infant', 'Child'],
    warnings: '5-HT3 antagonist. May cause constipation. Risk of QT prolongation at high doses.',
    searchTerms: ['nausea', 'vomiting', 'antiemetic'],
    isActive: true,
  },

  // VITAMINS & SUPPLEMENTS
  {
    name: 'Vitamin K (Phytomenadione)',
    brandNames: ['AquaMEPHYTON'],
    category: MedicationCategory.Vitamin,
    commonDoses: ['1mg', '0.5mg (preterm)'],
    routes: ['IM', 'PO', 'IV'],
    frequencies: ['Single dose at birth'],
    indication: 'Hemorrhagic disease of newborn prophylaxis, vitamin K deficiency',
    applicableUnits: [Unit.NICU, Unit.SNCU],
    ageGroups: ['Newborn', 'Preterm'],
    warnings: 'Routine prophylaxis at birth. IM preferred route. IV route has anaphylaxis risk.',
    searchTerms: ['vitamin', 'newborn', 'hemorrhage', 'vkdb'],
    isActive: true,
  },
  {
    name: 'Vitamin D',
    brandNames: ['Cholecalciferol'],
    category: MedicationCategory.Vitamin,
    commonDoses: ['400 IU', '800 IU', '1000 IU'],
    routes: ['PO'],
    frequencies: ['OD'],
    indication: 'Vitamin D deficiency, rickets prevention, supplementation',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.GENERAL_WARD],
    ageGroups: ['Newborn', 'Preterm', 'Infant', 'Child'],
    warnings: 'Routine supplementation for all infants. Monitor calcium levels.',
    searchTerms: ['vitamin', 'rickets', 'bone health'],
    isActive: true,
  },
  {
    name: 'Calcium Gluconate',
    brandNames: [],
    category: MedicationCategory.Vitamin,
    commonDoses: ['100mg/kg', '200mg/kg'],
    routes: ['IV', 'PO'],
    frequencies: ['PRN', 'TID'],
    indication: 'Hypocalcemia, calcium supplementation, cardiac arrest',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Preterm', 'Infant', 'Child'],
    warnings: 'Infuse slowly IV. Extravasation causes tissue necrosis. Monitor serum calcium.',
    searchTerms: ['calcium', 'hypocalcemia', 'electrolyte'],
    isActive: true,
  },
  {
    name: 'Iron (Ferrous Sulfate)',
    brandNames: ['Fer-In-Sol'],
    category: MedicationCategory.Vitamin,
    commonDoses: ['2mg/kg elemental iron', '3mg/kg', '6mg/kg'],
    routes: ['PO'],
    frequencies: ['OD', 'BD'],
    indication: 'Iron deficiency anemia, anemia of prematurity',
    applicableUnits: [Unit.NICU, Unit.SNCU, Unit.GENERAL_WARD],
    ageGroups: ['Newborn', 'Preterm', 'Infant', 'Child'],
    warnings: 'Give between meals for better absorption. May cause constipation. Stains teeth.',
    searchTerms: ['anemia', 'iron', 'supplement'],
    isActive: true,
  },

  // IV FLUIDS & ELECTROLYTES
  {
    name: 'Normal Saline (0.9% NaCl)',
    brandNames: ['NS', 'Sodium Chloride 0.9%'],
    category: MedicationCategory.Fluid,
    commonDoses: ['10ml/kg bolus', '20ml/kg bolus'],
    routes: ['IV'],
    frequencies: ['PRN for resuscitation', 'Maintenance'],
    indication: 'Fluid resuscitation, hypovolemia, maintenance fluid, drug dilution',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU, Unit.GENERAL_WARD],
    ageGroups: ['Newborn', 'Preterm', 'Infant', 'Child'],
    warnings: 'Isotonic crystalloid. Monitor for fluid overload. Can cause hypernatremia.',
    searchTerms: ['fluid', 'resuscitation', 'iv', 'saline'],
    isActive: true,
  },
  {
    name: 'Dextrose 5% in Water (D5W)',
    brandNames: ['5% Dextrose'],
    category: MedicationCategory.Fluid,
    commonDoses: ['Maintenance fluid'],
    routes: ['IV'],
    frequencies: ['Continuous'],
    indication: 'Maintenance fluid, hypoglycemia correction',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Preterm', 'Infant', 'Child'],
    warnings: 'Monitor blood glucose. Risk of hyponatremia. Not for resuscitation.',
    searchTerms: ['fluid', 'dextrose', 'glucose', 'iv'],
    isActive: true,
  },
  {
    name: 'Dextrose 10% in Water (D10W)',
    brandNames: ['10% Dextrose'],
    category: MedicationCategory.Fluid,
    commonDoses: ['GIR 4-8mg/kg/min'],
    routes: ['IV'],
    frequencies: ['Continuous'],
    indication: 'Hypoglycemia, preterm neonate fluid, high glucose requirement',
    applicableUnits: [Unit.NICU, Unit.SNCU],
    ageGroups: ['Newborn', 'Preterm'],
    warnings: 'Monitor blood glucose frequently. Risk of hyperglycemia. Central line preferred.',
    searchTerms: ['fluid', 'dextrose', 'glucose', 'hypoglycemia'],
    isActive: true,
  },
  {
    name: 'Ringer Lactate (RL)',
    brandNames: ['Hartmann Solution'],
    category: MedicationCategory.Fluid,
    commonDoses: ['10ml/kg bolus', '20ml/kg bolus'],
    routes: ['IV'],
    frequencies: ['PRN for resuscitation', 'Maintenance'],
    indication: 'Fluid resuscitation, burns, trauma, hypovolemia',
    applicableUnits: [Unit.PICU, Unit.HDU, Unit.GENERAL_WARD],
    ageGroups: ['Infant', 'Child'],
    warnings: 'Balanced crystalloid. Contains lactate (converted to bicarbonate). Avoid in hyperkalemia.',
    searchTerms: ['fluid', 'resuscitation', 'iv', 'rl', 'hartmann'],
    isActive: true,
  },
  {
    name: 'Sodium Bicarbonate',
    brandNames: ['NaHCO3'],
    category: MedicationCategory.Fluid,
    commonDoses: ['1mEq/kg', '2mEq/kg'],
    routes: ['IV'],
    frequencies: ['PRN for acidosis'],
    indication: 'Metabolic acidosis, hyperkalemia, cardiac arrest resuscitation',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Preterm', 'Infant', 'Child'],
    warnings: 'Infuse slowly. Extravasation causes tissue necrosis. Monitor pH and electrolytes.',
    searchTerms: ['acidosis', 'bicarbonate', 'electrolyte', 'code'],
    isActive: true,
  },

  // ANTICOAGULANTS
  {
    name: 'Heparin',
    brandNames: [],
    category: MedicationCategory.Anticoagulant,
    commonDoses: ['10 units/kg/hr', '20 units/kg/hr', '100 units/ml flush'],
    routes: ['IV infusion', 'IV flush'],
    frequencies: ['Continuous', 'PRN for line flush'],
    indication: 'Thrombosis prevention, line patency, DVT/PE treatment, ECMO',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Infant', 'Child'],
    warnings: 'Monitor aPTT. Risk of bleeding. Protamine is reversal agent. Heparin-induced thrombocytopenia.',
    searchTerms: ['anticoagulant', 'blood thinner', 'clot', 'thrombosis'],
    isActive: true,
  },
  {
    name: 'Enoxaparin',
    brandNames: ['Lovenox', 'Clexane'],
    category: MedicationCategory.Anticoagulant,
    commonDoses: ['1mg/kg', '1.5mg/kg'],
    routes: ['SC'],
    frequencies: ['BD', 'OD'],
    indication: 'DVT/PE treatment and prophylaxis, thrombosis prevention',
    applicableUnits: [Unit.PICU, Unit.HDU],
    ageGroups: ['Infant', 'Child'],
    warnings: 'Low molecular weight heparin. Monitor anti-Xa levels. Adjust in renal impairment.',
    searchTerms: ['anticoagulant', 'blood thinner', 'clot', 'lmwh'],
    isActive: true,
  },

  // NEUROLOGY
  {
    name: 'Mannitol',
    brandNames: [],
    category: MedicationCategory.Neurological,
    commonDoses: ['0.25g/kg', '0.5g/kg', '1g/kg'],
    routes: ['IV'],
    frequencies: ['Q4-6H PRN'],
    indication: 'Raised intracranial pressure, cerebral edema',
    applicableUnits: [Unit.PICU, Unit.HDU],
    ageGroups: ['Child'],
    warnings: 'Osmotic diuretic. Monitor serum osmolality. May cause rebound ICP elevation.',
    searchTerms: ['icp', 'brain', 'diuretic', 'head injury'],
    isActive: true,
  },
  {
    name: 'Hypertonic Saline (3% NaCl)',
    brandNames: [],
    category: MedicationCategory.Neurological,
    commonDoses: ['2ml/kg', '5ml/kg'],
    routes: ['IV'],
    frequencies: ['PRN for raised ICP'],
    indication: 'Raised intracranial pressure, severe hyponatremia',
    applicableUnits: [Unit.PICU, Unit.HDU],
    ageGroups: ['Child'],
    warnings: 'Infuse slowly via central line. Monitor sodium closely. Risk of central pontine myelinolysis.',
    searchTerms: ['icp', 'brain', 'hyponatremia', 'sodium'],
    isActive: true,
  },

  // BLOOD PRODUCTS (informational)
  {
    name: 'Packed Red Blood Cells (PRBC)',
    brandNames: [],
    category: MedicationCategory.Other,
    commonDoses: ['10ml/kg', '15ml/kg', '20ml/kg'],
    routes: ['IV'],
    frequencies: ['PRN for anemia/bleeding'],
    indication: 'Anemia, acute blood loss, hemorrhage',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Preterm', 'Infant', 'Child'],
    warnings: 'Cross-match required. Infuse slowly. Monitor for transfusion reactions. Irradiated for neonates.',
    searchTerms: ['blood', 'transfusion', 'anemia', 'prbc'],
    isActive: true,
  },
  {
    name: 'Fresh Frozen Plasma (FFP)',
    brandNames: [],
    category: MedicationCategory.Other,
    commonDoses: ['10ml/kg', '15ml/kg'],
    routes: ['IV'],
    frequencies: ['PRN for coagulopathy'],
    indication: 'Coagulopathy, clotting factor deficiency, DIC',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Infant', 'Child'],
    warnings: 'Contains all clotting factors. Monitor for volume overload and transfusion reactions.',
    searchTerms: ['blood', 'transfusion', 'coagulation', 'clotting', 'ffp'],
    isActive: true,
  },
  {
    name: 'Platelet Concentrate',
    brandNames: [],
    category: MedicationCategory.Other,
    commonDoses: ['10ml/kg', '15ml/kg'],
    routes: ['IV'],
    frequencies: ['PRN for thrombocytopenia'],
    indication: 'Thrombocytopenia, platelet dysfunction, bleeding',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Preterm', 'Infant', 'Child'],
    warnings: 'Single donor platelets preferred for neonates. Monitor platelet count. ABO compatible preferred.',
    searchTerms: ['blood', 'transfusion', 'platelets', 'thrombocytopenia'],
    isActive: true,
  },

  // ADDITIONAL IMPORTANT MEDICATIONS
  {
    name: 'Naloxone',
    brandNames: ['Narcan'],
    category: MedicationCategory.Other,
    commonDoses: ['0.1mg/kg', '0.4mg', '2mg'],
    routes: ['IV', 'IM', 'Intranasal'],
    frequencies: ['PRN for opioid reversal'],
    indication: 'Opioid overdose, reversal of opioid-induced respiratory depression',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Infant', 'Child'],
    warnings: 'Opioid antagonist. May precipitate withdrawal in opioid-dependent patients. Short half-life - repeat doses may be needed.',
    searchTerms: ['reversal', 'antidote', 'opioid', 'narcan'],
    isActive: true,
  },
  {
    name: 'Atropine',
    brandNames: [],
    category: MedicationCategory.Cardiovascular,
    commonDoses: ['0.01mg/kg', '0.02mg/kg', '0.5mg minimum'],
    routes: ['IV', 'IM', 'Endotracheal'],
    frequencies: ['PRN for bradycardia'],
    indication: 'Bradycardia, cardiac arrest, pre-intubation (antisialagogue)',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Infant', 'Child'],
    warnings: 'Anticholinergic. Tachycardia, dry mouth, urinary retention. Minimum dose 0.1mg to avoid paradoxical bradycardia.',
    searchTerms: ['bradycardia', 'code', 'resuscitation', 'heart rate'],
    isActive: true,
  },
  {
    name: 'Adenosine',
    brandNames: [],
    category: MedicationCategory.Cardiovascular,
    commonDoses: ['0.1mg/kg', '0.2mg/kg', '0.3mg/kg'],
    routes: ['IV rapid push'],
    frequencies: ['PRN for SVT'],
    indication: 'Supraventricular tachycardia (SVT)',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Infant', 'Child'],
    warnings: 'Very short half-life. Push rapidly followed by flush. Causes transient asystole. Have defibrillator ready.',
    searchTerms: ['svt', 'tachycardia', 'arrhythmia', 'heart'],
    isActive: true,
  },
  {
    name: 'Amiodarone',
    brandNames: ['Cordarone'],
    category: MedicationCategory.Cardiovascular,
    commonDoses: ['5mg/kg loading', '10-15mcg/kg/min infusion'],
    routes: ['IV', 'PO'],
    frequencies: ['Loading then continuous or BD/TID PO'],
    indication: 'Ventricular arrhythmias, atrial fibrillation, cardiac arrest',
    applicableUnits: [Unit.PICU, Unit.HDU],
    ageGroups: ['Infant', 'Child'],
    warnings: 'Antiarrhythmic. Causes hypotension, bradycardia. Requires central line. Long half-life.',
    searchTerms: ['arrhythmia', 'vt', 'vf', 'cardiac'],
    isActive: true,
  },
  {
    name: 'Sildenafil',
    brandNames: ['Revatio', 'Viagra'],
    category: MedicationCategory.Cardiovascular,
    commonDoses: ['0.5mg/kg', '1mg/kg', '2mg/kg'],
    routes: ['PO', 'IV'],
    frequencies: ['TID', 'QID'],
    indication: 'Pulmonary hypertension, persistent pulmonary hypertension of newborn (PPHN)',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU],
    ageGroups: ['Newborn', 'Infant', 'Child'],
    warnings: 'Phosphodiesterase-5 inhibitor. Causes systemic hypotension. Monitor BP.',
    searchTerms: ['pphn', 'pulmonary hypertension', 'revatio'],
    isActive: true,
  },
  {
    name: 'Indomethacin',
    brandNames: ['Indocin'],
    category: MedicationCategory.Cardiovascular,
    commonDoses: ['0.1mg/kg', '0.2mg/kg'],
    routes: ['IV', 'PO'],
    frequencies: ['Q12-24H x 3 doses'],
    indication: 'Patent ductus arteriosus (PDA) closure',
    applicableUnits: [Unit.NICU, Unit.SNCU],
    ageGroups: ['Preterm', 'Newborn'],
    warnings: 'NSAID. Reduces renal perfusion and urine output. Monitor creatinine. Contraindicated in NEC, IVH, bleeding.',
    searchTerms: ['pda', 'ductus', 'cardiac', 'nsaid'],
    isActive: true,
  },
  {
    name: 'Alprazolam',
    brandNames: ['Xanax'],
    category: MedicationCategory.Sedative,
    commonDoses: ['0.005mg/kg', '0.01mg/kg'],
    routes: ['PO'],
    frequencies: ['TID', 'PRN'],
    indication: 'Anxiety, sedation',
    applicableUnits: [Unit.PICU, Unit.GENERAL_WARD],
    ageGroups: ['Child'],
    warnings: 'Benzodiazepine. Risk of dependence. Sedation and respiratory depression.',
    searchTerms: ['anxiety', 'benzo', 'sedation'],
    isActive: true,
  },
  {
    name: 'Dextrose 25% (D25)',
    brandNames: [],
    category: MedicationCategory.Fluid,
    commonDoses: ['2ml/kg', '5ml/kg'],
    routes: ['IV'],
    frequencies: ['PRN for hypoglycemia'],
    indication: 'Severe hypoglycemia',
    applicableUnits: [Unit.NICU, Unit.PICU, Unit.SNCU, Unit.HDU],
    ageGroups: ['Newborn', 'Preterm', 'Infant', 'Child'],
    warnings: 'Hypertonic solution - requires central line or dilute to D12.5. May cause thrombophlebitis.',
    searchTerms: ['hypoglycemia', 'glucose', 'dextrose', 'sugar'],
    isActive: true,
  },
  {
    name: 'Glycopyrrolate',
    brandNames: ['Robinul'],
    category: MedicationCategory.Other,
    commonDoses: ['0.005mg/kg', '0.01mg/kg'],
    routes: ['IV', 'PO'],
    frequencies: ['TID', 'PRN'],
    indication: 'Antisialagogue (reduce secretions), bradycardia',
    applicableUnits: [Unit.PICU, Unit.HDU],
    ageGroups: ['Child'],
    warnings: 'Anticholinergic. Tachycardia, dry mouth, urinary retention.',
    searchTerms: ['secretions', 'drooling', 'bradycardia'],
    isActive: true,
  },
];

export async function seedMedications(userEmail: string): Promise<{ success: number; failed: number }> {
  console.log('🌱 Starting medication database seeding...');

  let successCount = 0;
  let failedCount = 0;

  for (const med of COMMON_NICU_PICU_MEDICATIONS) {
    try {
      await addDoc(collection(db, 'medications'), {
        ...med,
        createdAt: new Date().toISOString(),
        createdBy: userEmail,
      });
      successCount++;
      console.log(`✅ Added: ${med.name}`);
    } catch (error) {
      console.error(`❌ Failed to add ${med.name}:`, error);
      failedCount++;
    }
  }

  console.log(`🌱 Seeding complete! Success: ${successCount}, Failed: ${failedCount}`);

  return { success: successCount, failed: failedCount };
}

export function getMedicationCount(): number {
  return COMMON_NICU_PICU_MEDICATIONS.length;
}
